### ISSUE TITLE
MP.io website main page] fixes (blog)addition

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#159]
under "check out our recent posts", format is off of 1 of the 3 blogs @rstjames, thanks for fixing it. 

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/10731224/62334105-1eaad500-b47b-11e9-8889-bfff5b47434d.png">

**Comment by rstjames** [comment]
@aeiras no idea how to fix this. I tried for a while yesterday.  I would need to bring in Andrii to clean this up. 
It seems to be the standard styling when having a redirect link used with the wp ui.

**Comment by rstjames** [comment]
@aeiras Andrii and I corrected the styling. All is looking better. I will look into the overall styling of the home page (3 blog posts) they don't look great because people do not put an image with the blog post. This is because people do not follow the documentation. 

<img width="1275" alt="Screenshot 2019-08-05 17 36 16" src="https://user-images.githubusercontent.com/12132146/62476598-9e9cac00-b7a7-11e9-9634-c8241fa4f825.png">
<img width="898" alt="Screenshot 2019-08-05 17 36 37" src="https://user-images.githubusercontent.com/12132146/62476599-9e9cac00-b7a7-11e9-83b2-cf8a479acdb6.png">

**Comment by aeiras** [comment]
Thanks to both of you @rstjames and Andrii for prioritizing fix today :) 

Ok, so can you please @rstjames  update the active MP during the mktg call, anyone who helps review and publish MP blogs needs to stop publishing blogs without headers until we find a fix to the styling. cool?
