### ISSUE TITLE
Cloud Native Unconference on 7th September in London

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#175]
Please sign up today for the #CloudNative #Unconference #Java on 7th Sept in London! https://meetup.com/Londonjavacommunity/events/263581234/ `@emilyfhjiang` will be there together with @gblondelle
 @DaschnerS
 @BillyKorando
 @spoole167
 @holly_cummins
 to talk about #MicroProfile #Jakarta #Microservices #Kubernetes #Istio.

**Comment by Emily-Jiang** [comment]
Please tweet this asap.

**Comment by aeiras** [comment]
wow @Emily-Jiang, 

This ticket is great. There is no template in the drive for 6 speakers. I am not sure design can be ready this week, MicroProfile has 2 designers, SOujava and TT-- but availability within the timeline, less than 1 week instead of 2 suggested makes it that we are likely to push the session via the MP retweet as done today from your fantastic tweet. :) 

- [ task] create a template that covers 6 speakers means that 4, 5 speakers templates are needed. Making a total of 3 new sessions templates. 

@rstjames given the dates, could you prioritize the creation of the 6 template within this week? 
I will create the tickets for the 3 templates after sending this msg.

**Comment by rstjames** [comment]
Sorry did not have time to get to this.
