### ISSUE TITLE
[MP- errors with Media push] Facebook- Informed  via this ticket 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#185]
Post seems to have nothing to do with MP. 

Please explain connection? or delete if it was done by _human error_

![FB- Nothing to do with MP](https://user-images.githubusercontent.com/10731224/64194317-aea1bd00-ce33-11e9-9047-b722d903d12e.PNG)

**Comment by cealsair** [comment]
There were a lot of content about MicroProfile and Quarkus at this event.

**Comment by OndroMih** [comment]
I can't find the tweet, was it deleted, @aeiras, @cealsair ? If yes, can we close this ticket?

I suggest simple rules for the future:

* specific resources from conferences - recordings and slides from MP talks, articles about MP - OK to promote
* general conference promo just because it has sessions about MP - not OK to promote
* if it's evident that a MP tweet is a general promotion (2nd case), anybody can delete the tweet without asking

This tweet looks more like the second case (general promotion), so I would delete it from MP handle but I think it's already delete.

**Comment by aeiras** [comment]
This ticket is about MP Facebook Ondro. link https://www.facebook.com/microprofile.io/posts/2203103483145528
