### ISSUE TITLE
[MP- errors with Media push] Facebook- Informed via this ticket

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#186]
what is the relation to MP? 
![FB](https://user-images.githubusercontent.com/10731224/64194448-ffb1b100-ce33-11e9-9def-0e20fdd1c800.PNG)

**Comment by cealsair** [comment]
JBoss EAP 7.2 supports MicroProfile

**Comment by OndroMih** [comment]
Is this really relevant now, @aeiras ? The tweet is from January so maybe we can close this ticket?

Just my 2 cents here, @cealsair, I think that the tweet would be OK if it clearly mentioned that that version of JBoss supports MicroProfile vX.Y. I'm not sure it does because only part of the message is visible on the screenshot.

**Comment by aeiras** [comment]
push is via FB, link https://www.facebook.com/microprofile.io/posts/1882727258516487
