### ISSUE TITLE
Cross post MP blog on Micro releases

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#209]
As discussed in the architecture call yesterday [1] I've created a blog post [2] explaining micro releases of MP specifications. Can this be posted also in the MP blog, please?

[1] https://docs.google.com/document/d/1uAKRymdAL5Wj1KADzrYKZzSnAFsq74lBfj8lxKQnI6I/edit#heading=h.60vspycf6uhr
[2] https://xstefank.io/2019/10/09/minor-patch-releases-in-microprofile/

**Comment by aeiras** [comment]
@xstefank Martin, 

Perfect opportunity for you to become the newest MP wordpress contributor. 
[click Call to Action: Become a MicroProfile Author](https://microprofile.io/blog/)

Of course, while at it, you are MOST welcomed to make the current guidelines better, efficient, clearer by submitting PRs against it as you see fit. :) Super fun!

**Comment by xstefank** [comment]
@aeiras thanks for the pointers. I've created #210. Should I close this issue? Can I also ask where I can find bigger MP logo images, please?

**Comment by aeiras** [comment]
@xstefank, using above follow up let me reply by sections:

I've created #210. **fantastic!**
 Should I close this issue? **yes, this issue is no informative :) **
Can I also ask where I can find bigger MP logo images, please? **if you mean MP logos, go to the MP drive: [MP drive choose DESIGN folder](https://drive.google.com/drive/folders/0B8_67yGf9LkLOTdPeHdRRl9aWG8)
If incorrect, please clarify. cheers

**Comment by xstefank** [comment]
Found everything I needed :) Thanks @aeiras!
