### ISSUE TITLE
[Blog] New blog post – Building Microservices with Jakarta EE and MicroProfile @ EclipseCon 2019

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#221]
Hello all,

I have created an (external) blog post that I would like to post on the MP blog. I have created a draft here:

https://microprofile.io/?p=6436&preview=true

I have followed the instructions for posting external posts to the MP blog, but I'm not sure it is in the right condition yet. Can anyone with WordPress skills please assist and in the end approve the post?

Thanks!

**Comment by aeiras** [comment]
@ederks85, 

You rock! :) 
I adjusted a few things in the description including the title. I did my best to keep your structure yet please do review and adjust as you see fits. 

A few things:

- [about speakers' tweeter/git ] Do you have the other 2 presenters tweeter or git handles? If yes, please add them to the blog. People first. 

- [ Sessions tutorial addition] thanks for enabling the creation of new category, Sessions under Tutorials. :) 

- [ adding useful links] do note that for Jakarta EE I added git and for MP the website.

**Comment by aeiras** [comment]
Most importantly, thanks for scaling your session beyond the time you gave it and making sure it is traceable and it provides value to old and new MicroProfilers! @ederks85

**Comment by ederks85** [comment]
Hi Amelia,

You're welcome, and thanks for the final adjustements to the post. I have added the Twitter handles of my colleagues to the post as you proposed.

**Comment by aeiras** [comment]
My pleasure, you kept your word & avoided procrastination Edwin, an
inspiration to all of us. :)

Do assume from the reader nothing when writing MP content. Things that are
true, most of us want 1 click instead of copy/paste, lol as such see latest
adjustments on the twitter handles. Please use format in the future. Cheers
with coffee!
Amelia Eiras
twitter.com/ameliaeiras
Tribe: http://tomitribe.com      https://tribestream.io
OSS:  http://microprofile.io     https://jakarta.ee

**Comment by aeiras** [comment]
My pleasure, you kept your word & avoided procrastination Edwin, an inspiration to all of us. :) 

Do assume from the reader nothing when writing MP content. Things that are true, most of us want 1 click instead of copy/paste, lol as such see latest adjustments on the twitter handles. Please use format in the future. Cheers with coffee!

**Comment by ederks85** [comment]
Yes, will do :)
