### ISSUE TITLE
Home Page - layout problems

### ISSUE THREAD

**Issue by rsoika** [microprofile/microprofile-marketing#224]
Hi,
once again I want to point out that on the microprofile homepage there are still layout problems in the different projects. 
Please take a look at the following screenshot from the 'health' module. 
![image](https://user-images.githubusercontent.com/1339124/69033106-79424f80-09de-11ea-9e5c-fd65d99557af.png)
Should this not be formatted in one block?

Also in the config module the formatting is strange:

![image](https://user-images.githubusercontent.com/1339124/69033178-aabb1b00-09de-11ea-87a8-b7572ceca2e4.png)

**Comment by aeiras** [comment]
Hi @rsoika, 

The Projects page is feed directly via Git activity and it seems not all Repos are connected so that needs fixing.   
The Projects tab needs MicroProfilers' attention. You are correct, yet it doesn't require human admins to update it via WordPress access. 

If you are able to send a quick note with this ticket to the forum &/or attend a MP Community call and add the topic to the agenda that would be ideal.

**Comment by aeiras** [comment]
also, your ticket topic seems to be correlated to this ticket https://github.com/eclipse/microprofile-marketing/issues/101

**Comment by jclingan** [comment]
Resolved.
