### ISSUE TITLE
[Architecture call 2020] Design & media to continue 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#228]
the call will be kept as it is, every 4th week. 

@rstjames lets create a fresh design with focus on the pics from the calls, [see ](https://drive.google.com/drive/folders/1_iIXdbuajMOT0ssSJ9xYJAcoCqmDluwr)or use the same one, it is up to you. :) Using your feedback, i have been taking screen shots of the MP hangouts I attend, those pics are twitted on the spot and also added to MP Mktg>Photos folder in the drive. 

- Lets keep same wording for the 2 media pushes. 

- lets keep the reminders twice before the call, as it is today. 

Any follow ups, do pull me in.

**Comment by rstjames** [comment]
@aeiras have an issue scheduling this. It seems nobody has made a new document for the 2020 notes. Will they continue in this document or create a new one? This is an issue because in all the tweets I will put this link and want to be **100%** sure it is correct. 

Let me know and I will push this forward.

**Comment by kenfinnigan** [comment]
It would likely go in the same document, but at present, I'm not sure if we will continue with meetings or attempt to do everything async going forward

**Comment by kenfinnigan** [comment]
Closing as these calls have been shifted to async
