### ISSUE TITLE
Update MP data sheet with MP 3.3

### ISSUE THREAD

**Issue by cealsair** [microprofile/microprofile-marketing#245]
MP data sheet needs to be updated with MP 3.3. information.

**Comment by cealsair** [comment]
Shabnam Mayel from the Eclipse Foundation usually helps with this task. I cannot find her in the assignees list, however.

**Comment by aeiras** [comment]
Hola Cesar, 

The MP presentation hasn't been updated since MP.3.1. Lets add @rstjames to this task to make sure that presentation can be adjusted by any of the Contributors under MP branding without EF holding the task. Thanks for this ticket that shows what needs improvement. Excellent form! 

if you are coming to DevNexus, see you next week! :)

**Comment by cealsair** [comment]
The updated data sheet is located here:
https://drive.google.com/open?id=1r9j1Ep9L6XbHqPHN7_-LWMmDnqvwe0nS

A BIG THANK YOU to Shabnam!

**Comment by cealsair** [comment]
This issue is complete. Closing.
