### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by jefrajames** [microprofile/microprofile-marketing#293]
First name: Jean-Francois
Last name: James
Preferred email: jefrajames@gmail.com

**Comment by aeiras** [comment]
Beautiful Jean-Francois, 

You have been a MP wordpress contributor since the first week of January, 2019. 
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/10731224/87690144-e957cf80-c73d-11ea-8f2f-fb7349a41566.png">

I hope to remind you that you could crosspost to this site all your MP video, demo, blog content-- should you wish to do so. :) 

Stay healthy and awesome, abrazos fuertes amigo bello!
