### ISSUE TITLE
[DOC]Website link to presentation page is missing

### ISSUE THREAD

**Issue by iberrada** [microprofile/microprofile-marketing#295]
Hello

In the website the ressource referenced by the link https://microprofile.io/presentations is missing i.e. 404 error

Kind Regards

**Comment by aeiras** [comment]
Thank you for submitting the issue @iberrada.

@rstjames can you please help us find the issue? Thanks

**Comment by rstjames** [comment]
Hello @aeiras & @iberrada 
The link is missing because this page doesn't exist. "presentations" doesn't have its own page, it is found on the "resource" page. If you want to link to it you can we have an "anchored link" to the Presentation card on the resource page.  https://microprofile.io/resources/#presentation

Is this what you were looking for? 

R

**Comment by aeiras** [comment]
Ryan, 

Thank you for the prompt status follow up. 

@iberrada do you understand how you can gain access to the MicroProfile Releases presentation? 
Do note that the presentation contains all the past releases up until MP 3.2 (Feb. 2020) as the tracing for the releases beyond the MP Repo. 

Thus far, we have never traced how valuable the document is for users.  If you could share some insight of how you are using it etc that would be a fantastic insight.
