### ISSUE TITLE
Submitting a "post review" :D

### ISSUE THREAD

**Issue by gabrielbussolo** [microprofile/microprofile-marketing#299]
post about Setting up a "Jakarta EE development enviroment with SDKMAN, Eclipse and TomEE MP"
link to wordpress: https://microprofile.io/wp-admin/post.php?post=6576&action=edit
link to official post: https://gabrielbussolo.dev/blog/setting-up-a-jakarta-ee-development-enviroment-with-sdkman-eclipse-and-tomee/
thanks

**Comment by aeiras** [comment]
Hola @gabrielbussolo, 

Thank YOU for choosing to becoming a MP content contributor!!! 

Your blog is published. 
Please note a few changes as follows:

- Title uses capital letters & no abbreviations, it starts with the word Tutorial -- this doesn't mean you ought to change the title of your original blog, but you could if you want to :) 

- the word "guys" is replaced by folks -- inclusivity matters 

- when writing content we expect the content to be live a long time, we must always assume 2 things: 

1. the reader know nothing, so links to websites, etc are valuable & thoughtful (keeping the reader 1 click away matters to respecting his/her time)

2. the reader is someone busy that could be doing anything else instead of reading your tutorial. In short, how much time are you asking a developer to take owning your tutorial? The minutes **need/ought** to be stated on the first paragraph of your blog. 
As such, what do you think about adding an approximate time on completing the Tutorial (minutes)- how much time did it take you to start-finish the tutorial?  Such information is valuable and most important b/c it shows care to state the facts of what you as the author expect as someone teaching the tutorial. 

Lastly, you need to add your pic and a short bio to your Contributor access in MP wordpress. None can help you on that fun detail. 
<img width="807" alt="image" src="https://user-images.githubusercontent.com/10731224/88963294-7d588980-d25c-11ea-8857-5de9326a0f52.png">

Questions, shoot-- and it is an honor for me to edit & publish your very 1st MP content contribution via this ticket! :)

**Comment by gabrielbussolo** [comment]
@aeiras thanks for the advice and encouragement, i'll be more attentive when writing the next post. :smile:

**Comment by gabrielbussolo** [comment]
I added a profile pic and updated the content of the post at the original site.

**Comment by aeiras** [comment]
My pleasure Gabriel!
