### ISSUE TITLE
Request for reviewing new post

### ISSUE THREAD

**Issue by hbelmiro** [microprofile/microprofile-marketing#312]
Can anyone review my new post please?
https://microprofile.io/wp-admin/post.php?post=6599&action=edit

**Comment by aeiras** [comment]
I am on it @hbelmiro! : )

**Comment by aeiras** [comment]
Helber, 

I have read your blog, valuable as it is a tutorial. 
Please note changes:

- title adds Tutorial

- blog categorias add example and tutorial

- b/c this is a crosspost from your already public blog, I chose the Conclusion of your article instead of copy/paste the intro of your blog. The reason is that we need a thesis to tell the reader what they will achieve if they consume the content of the blog. 

- note that a few adjustments were added, but you could change them back, it is your call. I have dropped the "we" to DEVELOPER & CODER, ideally you educate your readers so that it is a group of coders, right who will benefit from the tutorial. 

You are always welcomed to use the MP content drive draft space, IF YOU WANT copy/edit support on your MP content.  MicroProfile when asked, do provide not native speakers English support. :) As a Latina, it is wonderful to have that access when dealing with e-books, white papers, that are 100% COMMUNITY OWNED. It is your call, it depends on your speed & on your willingness to work with others on content before publication. 

Here is the [collaborative space that allows anyone in the Web to be a part of the draft collaborate efforts on MP. :)  ](https://drive.google.com/drive/u/0/folders/1yonVuzmgpH_Mr3WgoqQEYywoJJjOmKBD)

let me know when the Tutorial is ok to publish and done! :) you are rocking it!

**Comment by aeiras** [comment]
also, examples of e-books written in a manner similar to yours are tickets:

https://github.com/eclipse/microprofile-marketing/issues/1
https://github.com/eclipse/microprofile-marketing/issues/3

and a few others that are blogs first yet they become e-books b/c of the aggregate value on diverse blogs that help others code with MP APIs :) super fun!

**Comment by hbelmiro** [comment]
@aeiras  Thank you so much for the feedback.
I will use your tips to adjust the whole text.
I left the blog public so you could read it when I created the issue. But I haven't shared links to it yet.

It's great to know about the draft space. May I ask you some questions about it?

- I saw that there are drafts of blogs at the drive, but you mentioned only e-books and white papers. Does MP provide support for blogs as well?

- If yes, could it had been used in this case, when the blog is not hosted by MicroProfile?

- What would be the best way to ask for support? Would it be creating an issue like this one?

**Comment by aeiras** [comment]
Happy Wednesday @hbelmiro, 

**Q:**  I saw that there are drafts of blogs at the drive, but you mentioned only e-books and white papers. Does MP provide support for blogs as well?
**A:**  Yes, the MP community supports blog reviews, copy/edit & technical reviews :) 

**Q:** If yes, could it had been used in this case, when the blog is not hosted by MicroProfile?
**A:**   if MicroProfilers collaboration occurs, we expect tracing on the work and that means that the MP blog _original content_ **IS** most likely first published in the MP blog. NOW,  the author can copy/paste the blog into its personal blog as well :) Win/win

**Q:** What would be the best way to ask for support? Would it be creating an issue like this one?
**A:**  Yes, creating a git issue if it deals only with copy/edit review. 
**A:**  heavy technical MP blogs need to use Git & allow for PR review to take effect. Usually the author uses its own Repo space to enable those PR reviews that include testing, etc. 
Examples are Cicek's e-book. He started like you, by writing blogs on what he was learning & then after awhile, he had so much valuable content that he moved the content to his Git from the drive to enable technical review.  As you see in his ebook, it lists the MicroProfilers who chose to participate :)   It is up to you to start the review, EARLY or later. 
**A:**  technical requests once the PR collaboration is set-up ought to be sent to the MP general forum asking for anyone to help. :) Also, it is helpful for the author to join the MP Community call before sending that email to make sure that many are aware of it before the email arrives to the forum.  

Helber can you submit a PR to the MP Content contribution guidelines with the Q&A & draft review link please? 
Your questions are excellent, i believe you have earned the opportunity to make the suggested [guidelines ](https://github.com/microprofile/wpsite)better with this conversation :)

**Comment by hbelmiro** [comment]
Hi @aeiras.

Sure I can do it.

I haven't finished editing my blog with your suggestions. I will let you know when it is ready to be published on the MP blog.

**Comment by hbelmiro** [comment]
Hi @aeiras 👋
PR submitted.

**Comment by hbelmiro** [comment]
Hi @aeiras.
I finished editing my blog. It's ready to be published.
Thank you so much for your help.

**Comment by aeiras** [comment]
Helber, 

Your 2nd MP blog is published! :) Should you tweet, remember to use @MP handle so that the handle could re-tweet your blog!
