### ISSUE TITLE
Add compatibility page for Implementations on microprofile.io

### ISSUE THREAD

**Issue by BaptisteMeynier** [microprofile/microprofile-marketing#321]
I'm looking for a page referencing all MicroProfile implementations similar to https://jakarta.ee/compatibility/ on microprofile.io. After some searchs I find informations from two others websites https://wiki.eclipse.org/MicroProfile/Implementation
and from https://start.microprofile.io/.

**Comment by cesarhernandezgt** [comment]
Indeed I see a design challenge by the amount of information the table https://wiki.eclipse.org/MicroProfile/Implementation page has. Can this be simplified by adding to the existing microprofile.io a  link to that tables?

**Comment by aeiras** [comment]
It is so wonderful  to see you in this project as well @BaptisteMeynier :) 

Perfect timing as the MP community is updating the website to be more developer friendly. 
See https://github.com/eclipse/microprofile-marketing/issues/285
& next ticket https://github.com/eclipse/microprofile-marketing/issues/320

Though your ticket is focused on implementations, do note that it relates to the MP website and as such relevant to current conversations. 

cheers

**Comment by Emily-Jiang** [comment]
+1 to @cesarhernandezgt ! We should add a link to the impl from the main landing page.

**Comment by keilw** [comment]
There's a bit of a "version-hell" with MP that even a different layout won't change, so linking from the initial page to that Wiki page sounds good. It also shows that a few specs have very few implementations while others have quite a few or at least several versions of the same implementation. 
Maybe if the whole MP WG is up to speed, it could be an idea to separate some of the individual specs and features from the umbrella, that would unclutter the whole page a bit.

It also shows TomEE is lagging behind compatibility tests with MP as well, since the last Final release compatible with anything was 7.0.x with MP 1.0. Or someone did not find the time to update that? https://github.com/jakartaee/collateral/issues/1 shows, the Jakarta EE compatibility simply wasn't done for TomEE at all, while the Wiki page about MP compatibility any Eclipse web user could theoretically change and there is no proof of the TCK results either unlike Jakarta EE.

**Comment by aeiras** [comment]
Hola BaptisteMeynier, 

Wonderful to see you in the MP repo! 

Today we launch the new MPWG page and will continue improvements as MP 4.0 release work continues. 

I will close this ticket b/c 2021 will help us figure out how the MP Compatibility page as well as the new Project's page. All coming in 2021. You are most welcomed to join that work Baptiste! 

happy holidays to you and thanks for your input here.
