### ISSUE TITLE
Request for microprofile.io post review 

### ISSUE THREAD

**Issue by rzgry** [microprofile/microprofile-marketing#333]
Announcing Language Server for Eclipse MicroProfile and the Tools for MicroProfile VS Code extension - https://microprofile.io/wp-admin/post.php?post=6624&action=edit

**Comment by aeiras** [comment]
Hola Ryan @rzgr, 

Your blog is now published-- Congratulations on your very first content MP wordpress blog, amazing content!
when you tweet, please keep in mind to use @[MP handle] so that the project gets the notification and if relevant, your BLOG is relevant, re-tweet you.  
 
During the blog review four (4) things need your attention:

- Your MP wordpress account requires your picture (see below), can you please update your profile?

-  Title change to _Announcement:_  AND MicroProfile stands alone as just MP, its original name under the MPWG. I have taken the liberty to cut Eclipse from the name, yet please keep in mind the name on future MicroProfile work. :) 

- As a writer, assume the reader knows nothing and do add the links of projects mentioned etc. I added the 3 projects links directly for you and expect you to keep this in mind on future contributions. 

- Your blog helps add LSP4MP as a new category in the MP blog. Thanks! - remember on next iteration to look for all cathergories and submit requests (via this channel) for missing ones when you think necessary. I added the projects you mentioned in the intro as categories as well, see below how your contribution is counted. 

Stay safe and rocking,

**Comment by rzgry** [comment]
@aeiras Realized I forgot to update the banner image after the extension was renamed to Tools for MicroProfile 😅 Is it possible to get the banner image updated to this: 
<img width="1369" alt="Screen Shot 2020-09-25 at 4 32 04 PM" src="https://user-images.githubusercontent.com/16768710/94313524-e0108d80-ff4c-11ea-9342-55c0f53019a5.png">


I dont seem to be able to edit the post now that it is published.

**Comment by aeiras** [comment]
Hey Ryan, 

I tried and I think it worked but it was not easy for me either. Maybe it is a bug. I will re-open this ticket until you check it out and see if it actually fixed the issue.

**Comment by rzgry** [comment]
Looks like it is fixed now, thanks!
