### ISSUE TITLE
[Dmitry Kornilov] Submission of committer quote

### ISSUE THREAD

**Issue by m0mus** [microprofile/microprofile-marketing#380]
I am leading the project Helidon - Java framework for developing microservices. MicroProfile is a proven industry standard. It’s in high demand. That’s why we’ve been implementing it since version 1.1 and will continue working on implementing its new versions. I like the community driven, effective and enjoyable approach of creating cloud-native APIs invented by MicroProfile. 
Dmitry Kornilov, MPWG Committer

Name: Dmitry Kornilov
Title: Director of Software Development
Twitter: @m0mus
Blog: https://dmitrykornilov.net
Bio: https://www.linkedin.com/in/dkornilov/
Github: @m0mus

**Comment by aeiras** [comment]
Hola Dmitry, 

Please review, adjust as you see fit the **quote's suggestions:** the word count is now 60 words :) 

_I lead the project Helidon, a Java framework for developing microservices. The MicroProfile technology is a proven industry standard. It’s in high demand. That’s why under Oracle, we’ve been implementing it since version 1.1 and will continue working on implementing its future versions. I like the community-driven, effective, and enjoyable approach of creating cloud-native APIs invented by the MicroProfile Community._      MPWG Contributor

**Comment by aeiras** [comment]
inventing "with" the MP ...

**Comment by m0mus** [comment]
It looks good. Please use this version with one minor change:

I lead the project Helidon, a Java framework for developing microservices. The MicroProfile technology is a proven industry standard. It’s in high demand. That’s why in Helidon we’ve been implementing MicroProfile since version 1.1 and will continue working on implementing its future versions. I like the community-driven, effective, and enjoyable approach of creating cloud-native APIs invented by the MicroProfile Community. MPWG Contributor

**Comment by aeiras** [comment]
fantastic Dmitry. 
https://docs.google.com/spreadsheets/d/14iCNpzj7BpvntOKG3u2ooEa-7LFceZTqk9OmqVqbDog/edit#gid=2050936009 
quote is added to export sheet. Should you want to add a picture as you see in the individual contributor's quote, please add it to this ticket. 
Either way, thanks for choosing to participate. Close the ticket as you see fits. :)

**Comment by rstjames** [comment]
added to the site
