### ISSUE TITLE
[Payara] Submission of Corporate Quote

### ISSUE THREAD

**Issue by rdebusscher** [microprofile/microprofile-marketing#396]
Quote from Steve Milledge regarding MicroProfile

Payara has been part of the MicroProfile initiative from the first launch announcement. We firmly believe in the strength and benefits of multi-vendor open standards and have been big advocates for MicroProfile from the start. In particular, we are keen to support the experimental and innovative approach to the creation of new open standards for microservice API development. One of the key goals of the Payara team is ensuring that we can ship products for developers that enable them to create applications using both the Jakarta EE and MicroProfile APIs. Therefore, one key aspect of our Working Group involvement is defining the relationship between the two.

**Comment by aeiras** [comment]
Hola Rudy, 

I am the reviewer of quotes for Feb, lets tackle Payara's quote that will be added to the MPWG Prospects' presentation :) 

Original Word count:  110

Review word: 75

Payara has been part of the MicroProfile initiative since its 2016 announcement. We are keen to supporting the experimental and innovative approach in the creation of new open standards for microservice API development. The Payara Team ships products for developers that enable them to create applications using both the Jakarta EE and MicroProfile APIs. One key aspect of our Working Group involvement is defining the relationship between the two.

Please review, if you can keep the word count to 80 that would be great. 
Note that the MPWG prospect needs to contain this & other's members' quote so the size is limited yet much more flexible than the 60 word count expected for Community quotes.

**Comment by ghost** [comment]
Hi Amelia,
 Stepping in for Rudy on the Payara quote revisions.

Revised word count: 80

"Payara has been part of the MicroProfile initiative since its 2016 announcement. We believe in the benefits of multi-vendor open standards and are keen to support the experimental and innovative approach in the creation of new open standards for microservice API development. The Payara Team ships products for developers that enable the creation of applications using both the Jakarta EE and MicroProfile APIs, and so a key aspect of our Working Group involvement is defining the relationship between the two."

**Comment by aeiras** [comment]
Wonderful Debbie!

The quote is now added to [sheet](https://docs.google.com/spreadsheets/d/14iCNpzj7BpvntOKG3u2ooEa-7LFceZTqk9OmqVqbDog/edit)

It will also be added to the MPWG Prospectus document.

**Comment by rstjames** [comment]
updated
