### ISSUE TITLE
Tweeter Poll 4- Jakarta EE 9 Alignment Questionnaire

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#428]
Question 4: Q4: Do you hope to start migration from the javax to jakarta namespace in the next year?

- Yes
- No
- Unsure

**Comment by aeiras** [comment]
Great addition, this will go as 2nd question.

**Comment by aeiras** [comment]
Sent and it runs for 4days: https://twitter.com/MicroProfileIO/status/1366784499468541957?s=20

**Comment by aeiras** [comment]
Emily, based on today's call, I am thinking that it could be great for MP to run a twitter poll with this question every 3 months. 
What do you think?

**Comment by Emily-Jiang** [comment]
I am not sure why we need to run the poll after we have made a decision. However, I think from now on, we should use twitter poll more to get community feedback on various issues or technical feedback etc.

**Comment by ederks85** [comment]
@Emily-Jiang I agree, we should never guess the opinion of the community and act on their feedback combined with that of the MicroProfile partners. Simple things like Twitter polls seem to work really well for this, reaching our target audience in the process

**Comment by aeiras** [comment]
Emily and Edwin, 

The question is not about alignment but about migration. We are blind, so I think it is a wonderful idea to schedule the poll question above every 3 months to track changes on migration to the technology or leaving the technology. 

Since lack of tooling and features are not helping with adoption, we want to pay close attention to potential improvements as tooling and features become available.   

This I will recommend on marketing as a set-process where we prioritize such action. :) 
Given current work, I think if we can improve what it is, that is always fantastic. More eyes, like the 2 of you, are valuable to this idea that is about to be pushed as a standard.

**Comment by aeiras** [comment]
Drive [results](https://drive.google.com/drive/u/0/folders/1LtiInEuIwt4BVmhPqHgLds8ETSa50Dtl)
[Twitter ](https://twitter.com/MicroProfileIO/status/1366784499468541957?s=20)
