### ISSUE TITLE
[Mktg-Call Steward] co-host for March

### ISSUE THREAD

**Issue by mehmandarov** [microprofile/microprofile-marketing#429]
Hi @aeiras! Re. what you mentioned on the call today – I'd be happy to help co-hosting the call in March.

**Comment by aeiras** [comment]
Thank you for choosing to step in to contribute, Rustam, @mehmandarov!  

You have edit access to the Stewards' sheet and can help adjust stuff, especially responsibilities. Please take the time to navigate responsibilities.  It doesn't mean you have to do the tasks. It means you are a watcher to move stuff forward. https://docs.google.com/spreadsheets/d/1gb2D8wPoXIrvmndMt0fP4jDYC61YuvBwVEFqVskywU8/edit#gid=0

Let's leave this ticket open. The important part is for you to help document stuff as you onboard into navigating the business side of MP. 
Use the MP [Drive Community ](https://drive.google.com/drive/folders/1EUEsKegOlN22u5u6CpPwmglEkJs_oc0f)to create documents relevant to the tasks that might be missing. If you help write any of the documents, they will become wikis and welcome PRs, as you saw today. :) 

Abrazos,

**Comment by mehmandarov** [comment]
Awesome! Thanks!

I created a doc explaining how to get started as a steward and I intend add some info about the onboarding process as we go. Feel free to add any content: https://docs.google.com/document/d/1ayqaFoXGeTZdneL6U9oekaZP3LPe7PapTlg7jh7eD3M/edit

**Comment by aeiras** [comment]
Hola Rustam @mehmandarov,

Do you have the time copy/paste the agenda template for the next call either today or tomorrow?
MP work is fluid via the tickets, therefore the agenda is recommended within 24hrs after the call is completed. :) This is part of the documentation. 👍   Questions, welcomed. And nope, you are not expected to search stuff in git, what we need is the template so that closed tickets and work in progress tickets can be listed in the agenda sections. 

When we delay the proactive agenda write it, the work gets lost as 2 weeks pass. The agenda needs utmost care & update by anyone who is doing stuff. As a Steward, it is your job to make sure minutes are there welcoming input.

**Comment by aeiras** [comment]
Hola Rustam, 

Today, I copied/paste the agenda minutes so that the many tickets that have closed since the last meeting are traced without fail. 
Do note that early placement of the agenda is recommended, either the same day after the meeting ends or the day after. :) This  ought to be added to the onboarding wiki you are helping write 👍 

@mehmandarov, 
Since you will lead next week's mktg call, you need to also own the send of of the minutes to the Mktg forum on Thursday. Ideally, on that day or the day before you have gotten enough time to see what else might be missing from the conversation based on what you have seen in the mktg git, mktg forum & MP Community forum/. :)

**Comment by aeiras** [comment]
@@mehmandarov, 

1 of the monthly tasks is to help publish content in MP Wordpress. Do you want to own it? Learn how to do it? 
You are already a Contributor who has submitted 1 blog. 
I will upgrade you to Editor to enable you to review and maybe push content written by others. We ought to not push your own content or at least get other Editors to publish it for you. 

You have became the 12 Content Editor, today! :) 
Saying no to own the task is OK. Note that I am adjusting stuff to enable you to own responsibilities. Yet always keep in mind that you can ask others to help you as well. Being assign to a month doesn't mean you must do the work, it just means that you follow the process and make sure that stuff gets done in any way that brings collaboration and scales beyond you. : )

https://github.com/eclipse/microprofile-marketing/issues/452

**Comment by mehmandarov** [comment]
Sure, I can do that, @aeiras! Do we have guidelines for the content that we publish?

**Comment by aeiras** [comment]
[Blog Guidelines- Blog Call to Action space](https://microprofile.io/blog/)

**Comment by aeiras** [comment]
@mehmandarov Hola!

Would you like to do the honors on copy/pasting the agenda minutes for the [March 29th call](https://docs.google.com/document/d/1fQWUiCInhJni8WhGt2k5WKqb8K6BuhzzWTzqynvX3_U/edit#heading=h.r05m2a3vpboj)?
If yes, how does tomorrow sound? Ideally, the agenda is created within 24hrs after the marketing call. The MP work doesn't stop, as you can see, we use git issues and when closed, we tend to add them to the agenda to make sure that tracing is there. There is no agenda, so that will be problematic to older tickets that are closed. \

Thanks for your help,

**Comment by aeiras** [comment]
adding it as a topic item to next Monday agenda. Retrospective fun. Closing the ticket :)
