### ISSUE TITLE
CN4J Alliance Joined Message Draft - Review and Vote Due date April 12th

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#450]
This week, the 2 CN4J alliance call minutes were released to the MP and Jkta communities. 
The 2 groups agreed that I could be great to start communicating and educating on the alignment of both technologies with David's and Will's draft that needs our attention. [Join Message](https://drive.google.com/drive/folders/1W-vXbSTTB8rwY0gKwgeg_Q8jlv6YlQip  
The 2 documents have been copied into the Community "public write/edit" folder and welcome MicroProfilers feedback via "suggested edit" and comments.  :) 

Announcement of the published minutes sent by John to the MP community forum sent on [3/11](https://groups.google.com/g/microprofile/c/ktLrkTLbozw) The documents are housed under the MPWG External folder >[CN4J Alliance](https://drive.google.com/drive/folders/15vagNfiTvxFq5dtAJLXQ89Kj54bMyCUs) approved documentation, minutes, and works.

**Comment by mehmandarov** [comment]
Should we add this to the call agenda to ask for more contributions, @aeiras? I am reading through the doc and adding my comments right now, but I suppose it can be good to have more contributors?

**Comment by aeiras** [comment]
Good you see that the task requires many eyes 👀 
It is already added to the agenda under Working group topics. Please add your name to it & adjust written stuff as you see fits. 

The ticket was sent to 3 channels: MP community, MP marketing & CN4J mailing lists. It calls out the need for participation & provides full access for anyone to show up via the documents & improve stuff. 

💛

**Comment by mehmandarov** [comment]
Awesome! 

Sincerely
Rustam 
still-on-training-wheels 🚲

**Comment by aeiras** [comment]
Thank you for choosing to show up & do the work 💞

**Comment by aeiras** [comment]
@rstjames 

This ticket contains the CN4J - Works [presentation](https://drive.google.com/drive/u/0/folders/1W-vXbSTTB8rwY0gKwgeg_Q8jlv6YlQip) shown this AM.  You have 100% liberty to adjust all the branding in the slides. The Trademark needs to be a 50%50 btw the 2 projects. 

Thank you for using this ticket and the CN4J drive to provide updates. There is also the CN4J mktg thread available.

**Comment by aeiras** [comment]
Hola @debbiehoffman & @TetianaFTV, 

I have reviewed the 1st draft of the document while attending the steering calls before publication.  
Do you have some time to help review the actual document? 
As stated on Monday's discussion, @rstjames will work on the slides to make them MP<>Jkta branding balance.

**Comment by TetianaFTV** [comment]
Hola @aeiras 
Can I approve the suggested edits inside this doc in order to see the clean current version of the document?
This will make the final review process easier and new suggestions from other reviewers more visible.
Anyway previous versions are stored in revision history in case anything should be reversed.

**Comment by aeiras** [comment]
Sure Tetiana, go at it! 💪🏼🥋

**Comment by rstjames** [comment]
@aeiras I am not sure what you want me to do here...

**Comment by TetianaFTV** [comment]
Hi, so here is **what I've done** today:
1) [messaging document](https://docs.google.com/document/d/1QEHWlIT7TmKE6xdfECvRrudRoGgJrHnd6jlkFvCUBVc/edit#):
- cleaned suggestions and comments
- reviewed the texts, edited distribution list and some texts in general

2) [presentation](https://docs.google.com/presentation/d/1wYBNqUHwADvipTC9fW5ugGMbDf_3_JH9skBtyPcI-IE/edit#slide=id.gc994ce748f_0_1): 
- offered new look for initial and final slides to make it both MP and Jakarta branded (previous are left marked as hidden)
- updated master layout for other slides
- remade the look of intro slides for MicroProfile and Jakarta EE (old ones are left marked as hidden)
- updated two slides with logos of compatible implementations
- added slide with tech supporters of both MicroProfile and Jakarta EE

**What is needed:**
1) update this scheme in the presentation
![pasted image 0 (1)](https://user-images.githubusercontent.com/38689227/111671640-71383100-8819-11eb-8a9e-eb52e9dfcca0.png)
- move Annotations to the center (half blue, half orange)
- rename outdated Java EE terms (e.g. JSF instead of Faces, JPA instead or Persistence etc)
- make the signs more contrasted and visible

@rstjames most likely this design task is for you
not sure who can help with updating the terms (or if you are aware of the right ones)

2) check the list of compatible implementations logo and leave a comment with the names of those that should be added / deleted

3) check the slide with tech supporters of both projects and extend it with the required names

4) approve with what look of intro slides we go and delete the outdated

5) In the document I left the comment "what is meant by sponsors and contributors here?"
so if someone can explain in short, please leave the answer there

@aeiras maybe you can help directing these tasks to the right people.

Thanks!

**Comment by aeiras** [comment]
Tetiana, 

As usual, your care shows through your feedback. 

[collaborative call next Tuesday 9:30 am-10:30 am PDT](https://www.eclipse.org/lists/cn4j-alliance/msg00122.html) will help anyone who wants to collaborate do so. 

I believe it is fantastic that a few of us can help now. Thank YOU for being that amazing, so much fun! I
It is likely that a new presentation will be created, likely using a few of the things in the one in existence. Diagrams are important to providing the visibility of how truly aligned the 2 technologies are. Your improvement on the APIs is amazing! 
We will need to create the same for implementations, members, etc. :)

**Comment by Emily-Jiang** [comment]
Thank you @TetianaFTV for leading this effor for further improvment! IIRC, on the call, there was a suggestion to convert this to be a wenn diagram.

**Comment by aeiras** [comment]
spot on Emily on visual need to be prioritized in all communications about MP<>Jkta
 
the slides will have many different Venn diagrams. I can count at the bare minimum 3, yet the more the better: 

- members 
- implementations
- APIs

**Comment by Emily-Jiang** [comment]
also Annotation should be put in the middle as both MP and Jakarta use it.

**Comment by aeiras** [comment]
Moved to MPWG repo
