### ISSUE TITLE
[MP Website] Update - MP Releases Presentation

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#460]
@rstjames, 

The actual presentation slides is updated to [MP. 4.0](https://docs.google.com/presentation/d/1tILNRRjr6jxIM77m6zQ4JQQdXpqkGIg0pQHcL9J3pog/edit#slide=id.ga6bdad56ea_0_7) However, that is a temporary link based on the release. We want to go back to the general link that contains all the Release history via presentations.

**Change:**

- Update the Trademark name, it is MP. 
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/10731224/111548735-5a6ddd80-8738-11eb-80e2-a6595dd6b3f8.png">

- what about adding an image from the presentation document into the page itself or something else in the landing page? It has no MP flavor. 

**Issue with the link:**

- MP 4.0 release in the marketing side was completed a day before X-Mas so a new Presentation was made with only MP. 4.0 dropping the past releases updates. 
- We need to update the Past Presentation to incorporate this document into 1 so that the link doesn't need to change. 
- Can you please update the document? [Here](https://docs.google.com/presentation/d/18CePEU9sMHKNRUzOZ2uzYKsh3ZyvC_P-OUhAvJTxNSg/edit#slide=id.p)

@rstjames what we want is to make sure that we don't need to update the link each time a new release happens. :) 

Pull me in if you have any questions,

**Comment by rstjames** [comment]
@aeiras 
It was set up before that we didn't need to update the link each time.. so what changed? 
I do not understand what you are saying about the issue with the link. If it's updating something on the drive please just do it. 

Updated the links and adjusted the image.

**Comment by aeiras** [comment]
Días Ryan, 

You & I were on vacation when the marketing formal announcement for MP 4.0 went out. Amazing Tetiana lead that effort the Xmas week with a few other MicroProfilers. Limited time caused a few short cuts. 

We need to fix stuff so that links are scalable. I will  adjust release documentation to what is already at hand to make sure link is not changed again. 

Thank you for your help,

**Comment by rstjames** [comment]
is this done? We can close it? 
@aeiras

**Comment by aeiras** [comment]
Nope. I think I will need to pull @jclingan to help on this one so that we can keep same link as it is now but make sure that the presentation is a 1 document continuing to be updated and placing its history within the document. 

Adding @jclingan here. :) I am pretty sure you helped with the MP 4.0 presentation update. It was X-Mas and super short time. 
**Issue:**

- MP. 4.0 presentation is just 1 document with solely MP. 4.0 linked in the website. 
- We need to make it so the past release presentations are added into this document so that the upkeep of the link doesn't ever change.  

Can you help with the copy/paste John?  
I will update the wiki write up if you do. Or lets figure out what do we need to do to make sure that less upkeep is needed.

**Comment by aeiras** [comment]
Also adding @ederks85 here :)

**Comment by TetianaFTV** [comment]
Let's sum up what we plan and what we have in order to move this task further.

We want to add the link to the folder with release presentations to the site https://microprofile.io/resources/#presentation in order not to update this link every time when we have a new presentation prepared. We will add the link to the subfolder of year 2021 and will be updating it annually afterwards.

Now all release presentations are stored together with release blog post drafts in [Blog Announcement and Presentations](https://drive.google.com/drive/folders/1LgxGyXwOjpJMkWBZZ5eVm8JpfLA7heS4) folder. I've already sorted them based on the year of the release to subfolders and created a new empty one for 2021.

### Is it ok to share subfolders of [Blog Announcement and Presentations](https://drive.google.com/drive/folders/1LgxGyXwOjpJMkWBZZ5eVm8JpfLA7heS4) at the site? Any objections or concerns?


**P.S.** some points to clean the folder:
- there is subfolder called [LatestReleasePreso-forMP.io
](https://drive.google.com/drive/folders/1VheJD9sJBiwfXSH1Lbc-eQtVuz4BFM6d) that includes a copy of the presentation for 3.3 release, so we need to archive this folder not to mislead people
- there is a presentation called [MicroProfile - high-level - generic - up to 3.3](https://docs.google.com/presentation/d/1iwdOIfE8KjDZpKI81_l6yoOK-Cjyvr-0gMmDYzW3Ow4/edit#slide=id.p) that looks like some draft, so it also should be archived not to mess up things

**Comment by rstjames** [comment]
is this ticket still valid... sorry didnt see movement on it. @TetianaFTV @aeiras

**Comment by TetianaFTV** [comment]
I think this task can be closed. When it's time to create a new presentation for upcoming release it's better to create a separate task with appropriate description.
So who has the rights, please close it.

**Comment by rstjames** [comment]
ok closing it
