### ISSUE TITLE
[Documentation] Twitter Usage Guidelines

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#483]
Based on nice exchange today https://github.com/eclipse/microprofile-marketing/issues/475#issuecomment-818202193, it is time for a form documented wiki where the usage of Media is stated and adjusted as we more forward welcoming new Contributors. 

To start, draft is here[Twitter usage guidelines](https://github.com/eclipse/microprofile-marketing/issues/475#issuecomment-818202193)

The document is public, @TetianaFTV and @debbiehoffman both of you have access to contribute in Twitter. It would be great for you to review and improve the document. Thank you!

**Comment by TetianaFTV** [comment]
@aeiras, let's clarify, your point here is that instead of just direct posting from MicroProfile Twitter account some prepared text, we need to follow the next steps
- a contributor of the article should post a tweet from personal account with MP tag
- MicroProfile will reshare that personal post
do I understand you correctly?

If so, I think here we need to prepare a guide not on the Twitter handling but on the blog posts contributions in general (from submitting to sharing).

As I've mentioned in the thread with Emily, I couldn't find any written rules on how to submit or who should approve the articles (maybe there is such document then please share it here). Soon there will be the same approval questions with these articles from Manish, so we need to come up with the process.

**Comment by Emily-Jiang** [comment]
Thank you @TetianaFTV for beating me rasing this issue! I think we need to define a process because I don't think we have a formal process to follow.

**Comment by Emily-Jiang** [comment]
I have raised [this](https://github.com/eclipse/microprofile-marketing/issues/484) issue to formally document the blog publishing process.

**Comment by TetianaFTV** [comment]
let's add the link to current guide here to keep all related info in the ticket
https://github.com/microprofile/wpsite

**Comment by aeiras** [comment]
You two could rule the world! :)

**Comment by aeiras** [comment]
Tetiana and Emily, 

Have we concluded the Q&A on contributing to social media tools? 
If yes, this document will be converted into a Mktg Wiki document https://docs.google.com/document/d/1O-p8HJxs13WEZs8Sl2NNrLuh4ofRngV_EKMDJJYa91g/edit

**Comment by TetianaFTV** [comment]
From my side no edits to the social media handling guide, so seems it can be converted to wiki.

**Comment by Emily-Jiang** [comment]
Agreed with @TetianaFTV ! Putting this doc in the wiki is good, as this is a process that will guide others in the future.

**Comment by aeiras** [comment]
Thanks you two! 

wiki created from old wiki bare version that linked to the document https://github.com/eclipse/microprofile-marketing/wiki/Code-of-Conduct-Standards-for-Social-Media-Contribution 

Show and tell on next mktg call.

**Comment by aeiras** [comment]
Hola @debbiehoffman, 

I will close this ticket with the export of the revised Twitter Guidelines converted into MPWG Wiki today.  https://github.com/microprofile/micropraofile-wg/wiki/Twitter-Usage-Guidelines

Can you please add 2 mins to the agenda for show and tell? **Thank you**. 
Once that is done, the wiki documents will be exported to the website under Resources /Media page & MPWG page. The google versions have been moved from Community "public edit" to the Admins restricted folder (no more changes without PRs),  

**Note** 

this wiki belongs to the Marketing repo. 
https://github.com/eclipse/microprofile-marketing/wiki/Code-of-Conduct-Standards-for-Social-Media-Contribution

This wiki belongs to the MPWG repo
https://github.com/microprofile/microprofile-wg/wiki/COC:-The-Social-Media-Standards
