### ISSUE TITLE
[Tweet] MicroProfile is celebrating being 5. What has MicroProfile helped you?

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#500]
I would like MicroProfile twitter handle to tweet this or something similar:
@MicroProfileIO is turning to 5. Time flies! We would love to hear what you think about MicroProfile. Please add your thoughts on this googledoc shorturl.at/otGJU

**Comment by aeiras** [comment]
shorturl.at/otGJU  from https://docs.google.com/document/d/1pONdhHeusGyyQbyMUw5ONTpEoD4LaMf7GPQsX_kl1-I/edit

**Comment by aeiras** [comment]
@Emily-Jiang, I am done with my review and additions. Thank you for pushing this during today's discussion. Amazing work! 
Please pull me in when you wish the tweet to go live on Wednesday.

**Comment by Emily-Jiang** [comment]
Thank you @aeiras ! I have accepted your suggestions. I think we are all set. Go ahead to send the tweet on Wednesday!

**Comment by aeiras** [comment]
Excellent, gracias Emily!

**Comment by aeiras** [comment]
MP [Tweeted ](https://twitter.com/MicroProfileIO/status/1397571657481351172?s=20) & pinned in to the profile.
@Emily-Jiang we skipped the deadline because we will use follow up tweet remiders. 
Are you ok to share the tweet via the Community forum to bring attention to the C2A? if so, yeay! 

@rstjames, 
Pulling you in. Can you please help schedule consecutive tweets that go on either saturday or Sunday, starting this weekend, through last weekend June 20th?  Suggestions on what other day tweet could go out welcomed. I haven't seen current schedule so your recommendation is key. :) Thanks Triber!

**Comment by rstjames** [comment]
Next time we should not put @ at the beginning of a tweet.  If a tweet starts with a username, Twitter thinks it's a conversation. And when tweeting from MicroProfilIO handle you don't need to put @ MicroprofileIO because its coming from that handle. 

Tweet: 
MicroProfile is turning 5 on June 27th. How time flies! We would love to hear what you think about💛 #MicroProfile. 
Please add your thoughts on this google document: https://bit.ly/3vqpkmr

#ByCommunityForCommunity #OpenSource #MovedByJava #OSS

Set to go out every sat till the 20th.

**Comment by aeiras** [comment]
Omgosh, Ryan. I finally understand. It won't happen again. Thank you for explaining it again. This time I think I got it. :)
