### ISSUE TITLE
[Swag] Ship MP t-shirt to Giuseppe 

### ISSUE THREAD

**Issue by gscaramuzzino** [microprofile/microprofile-marketing#523]
Hello,
I would like to wear a MicroProfile t-shirt to generate some brand awareness in France. If it is possible ship some stickers too.
I'm very happy to be part of this community and spread the voice of MicroProfile Specifications.
Thank you!

**Comment by aeiras** [comment]
Your mpSwag was sent yesterday!

If you would like the international tracker, please let us know. Next week, we can share it internally with you. :)

**Comment by gscaramuzzino** [comment]
Perfect. Thank you so much.
By the way the August 9th I am going to have a talk at the Quarkus Insight YouTube Channel:
"Quarkus projects using MicroProfile specs with Giuseppe"

**Comment by aeiras** [comment]
Omgosh, I hope your MP swag gets there on time so that you can use it for that talk and all your future MP sessions, workshops, etc @GiuseppeScaramuzzino !  Your sharing actions are truly amazing! 

Should you wish MP support, your MP activities could be easily highlighted.  You could submit git issues (as you see fit, no limits)  via this repo and follow the guidelines on how to **here**: https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support
The guidelines are also found on the website under Branding  & under Resources. As a user, you could help us make it easier to find too. Provide feedback as you see it fit via git tickets ok!

**Comment by gscaramuzzino** [comment]
Done.
Thank you for your help.
https://github.com/eclipse/microprofile-marketing/issues/539
