### ISSUE TITLE
[Website - MPWG Page]  2021 Budget Import

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#553]
The MPWG [Budget and program](https://microprofile.io/workinggroup/) plan can finally be populated. 

@rstjames can you think of a way to make this tab about budget and planning scalable to be able to hold 1 tab per year or similar? 

There are 3 parts of the documentation:

- [yearly Project + translations](https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C)
- the actual budget[ approved](https://drive.google.com/drive/folders/11RQe2ONXqqK4YQUfXtvNtMJYq_IfEiji) + ballot on members[ voting](https://drive.google.com/drive/folders/11RQe2ONXqqK4YQUfXtvNtMJYq_IfEiji)
-[ budget spreadsheet](https://docs.google.com/spreadsheets/d/1Xg0LbeQSH7MiJDmG_qm_BkcpK9Xacl2cE75fAzrEAOw/edit#gid=950497108), live - working document. 

**Issue I see**, how do we make it so each year, the tab can host both, past years and new years budgets, easily? 

Thanks for openly brainstorming, Ryan. 

I will do the write up on each part after discussion via this ticket.

**Comment by rstjames** [comment]
@aeiras It is not possible to put a tab section inside of a tab section. I think the only thing we can do is have that year's info and a link to past years where they will find all other past year documentation. Also how many people want to see immediately past years' budgets? If they want that info they are willing to dive a bit deeper into the documentation. 

Like this inside the tab:

**Version 1:**
**2021**
Project + translations
the actual budget approved + ballot on members voting
- budget spreadsheet, live - working document.

Past year budget documentation (link) _would take them to a doc that has all info and links for each year._ 

**Version 2** (I would not go this direction because not scalable later on)

**2021**
Project + translations
the actual budget approved + ballot on members voting
- budget spreadsheet, live - working document.

**2020**
Project + translations
the actual budget approved + ballot on members voting
- budget spreadsheet, live - working document.

**2019**
Project + translations
the actual budget approved + ballot on members voting
- budget spreadsheet, live - working document.

**Comment by aeiras** [comment]
Ryan, 

Excellent insight. Thank you, Ryan!
Let's go with your preferred choice. Clean & simple, I like it!  +1 from me. 

Adjustments, instead of "Project" lets replace it with Plan. 

If you need anything else, please pull me back in. A message for this was sent to the mktg forum to increase awareness of the work.

**Comment by aeiras** [comment]
Oh, the link for past years budget information covering  all years is this https://drive.google.com/drive/folders/1zi1MIEqv-I87NielCdLn6cCEfhwLRIGK

**Comment by rstjames** [comment]
@aeiras updated: 
https://microprofile.io/workinggroup/

![Screen Shot 2021-08-05 at 12 00 54 PM](https://user-images.githubusercontent.com/12132146/128331987-8098a1c1-353b-421d-a480-22c91d6cd68a.png)

**Comment by aeiras** [comment]
It looks pretty good, Ryan! 

Awesome work on scaling this for current and future intake. :) YOu rock!
