### ISSUE TITLE
MP Compatible logo voting progress 

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#591]
Here we can track the progress and document what work has been done to get to where we are now.

**Comment by rstjames** [comment]
I have gotten access to Survey Monkey and I am building the survey for voting on the MicroProfile Compatible logo.

**Comment by aeiras** [comment]
thank you, Ryan. 

For the tracing information in the ticket, we will add the MP Brand HandBook.  https://github.com/microprofile/microprofile-wg/issues/45

**Comment by rstjames** [comment]
@aeiras Have you had time to help with the intro content for the survey? 
We discussed having: 
- links to GitHub ( to all logo tickets? ) 
- Link to the pdf with all logos formatted (showing scalability of the logo) 
- description of what the process was and how we got to where we are now. 

![Screen Shot 2021-10-25 at 7 09 07 PM](https://user-images.githubusercontent.com/12132146/138740213-bc425ec9-dc98-4865-89b7-fdb4794dd014.png)

**Comment by aeiras** [comment]
@rstjames, 

Thank you for your work on this. 

- [ **Not needed**] links to GitHub ( to all logo tickets? )

- [ **YES** ] Link to the pdf with all logos formatted (showing scalability of the logo)

- [ **the insert of the Branding Manual goes into the C2A**  ] description of what the process was and how we got to where we are now.

**suggested description using your  good draft** :) 

Thank you for choosing to rank-vote which logo best represent the MicroProfile Compatible mark with 1 ( your **MOST** preferred logo) through 5 (your **LEAST** preferred logo) 

The MicroProfile Community came together to create diverse MicroProfile Compatible Logos submitted via git issues. The 5 participant [logos](https://drive.google.com/drive/u/0/folders/1unMeyPjVudkheFUKnpWYahAtAkT6An0b) have been discussed & tweaked at length.  For more information about MicroProfile Branding, check the [MP Brand Manual Guide.](https://drive.google.com/drive/u/0/folders/1zXwNllUjw3ftjsNdUVE7shmLe9UOuErc) 

**Testing Survey Monkey deadline and links, etc**
Thanks for updating the information and submitting a test vote  (Survey Monkey - 24hr deadline) via email to John, Ed, Debbie, Tetiana and myself. Though the plan is to use the mp community forum for the vote, the testing is helpful for final review.

**Comment by TetianaFTV** [comment]
Suggested edits to the wording on voting page:

### MicroProfile Compatibility Logo Voting

We are one step from choosing a final MicroProfile compatibility logo. The community submitted [5 diverse logo designs](https://drive.google.com/file/d/10WzrQiVZfLXRGv1a4rs0ht2SPG0pihUf/view?usp=sharing) and we adjusted them based on the [MicroProfile Brand Manual Guide](https://drive.google.com/file/d/1ZCsTPQ9yeDVHXCOGDqkLBbXva9JKV8AP/view?usp=sharing). 

Now we are looking forward to hearing your opinion in order to make a decision based on the community preferences. Please rank-vote which logo best represents the MicroProfile Compatible mark ( **1** being **MOST preferred** through **5** being **LEAST preferred** ).

**Comment by aeiras** [comment]
Link to updated requirements git issue https://github.com/microprofile/microprofile-wg/issues/107
