### ISSUE TITLE
[General: Mktg-Call Steward] co-host for Nov/Dec

### ISSUE THREAD

**Issue by caitmm43** [microprofile/microprofile-marketing#609]
Hi @aeiras, @TetianaFTV, I will be helping with co-hosting for November and December :) 

I've reviewed the MCSWD doc and completed action items 1-4 in the getting started checklist.  Next, I will wait for the confirmation.  

I am new to this process and platform so, while I always welcome feedback, I would especially appreciate it here.  I very much look forward to being involved!

**Comment by aeiras** [comment]
I am so happy to see this git issue arrive, @caitmm43!
MP is so lucky to get your time & contributions on behalf of the GSJUG. Neha contributions rock!  This is so fantastic! 

Onboarding you is going to be extra fun! 
You have edit access to the Monthly Mktg -Call Stewards. Do check it out and make sure to add stuff "Limitations" column: 
 https://docs.google.com/spreadsheets/d/1gb2D8wPoXIrvmndMt0fP4jDYC61YuvBwVEFqVskywU8/edit#gid=0

Whatever you do, do not stress about a thing and ask away using this ticket. 
We will learn with you while onboarding you :)

**Comment by aeiras** [comment]
Onboard you  @caitmm43, 

You now have:
1) Triage GH access to all MP repos: See yourself listed under the MP Infra webpage under Overview tab and check out your access . https://projects.eclipse.org/projects/technology.microprofile 
https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-“Triage”-access

2) MPWG Repo Write GH access https://github.com/microprofile/microprofile-wg/settings/access?guidance_task=

Please check your emails to accept the write access which is currently pending. 

This ticket will be open until December ends, we will use it to onboard you, Q&A, etc.

**Comment by caitmm43** [comment]
@aeiras I'm working through the [MP Git Issues Inventory ](https://github.com/eclipse/microprofile-marketing/issues?page=2&q=is%3Aissue+is%3Aopen) & adding to the Agenda.  I've gone as far back as September, adding all tickets that need follow up or closing.  

Looking at past minutes, it's clear that stewards do not add every existing ticket to the agenda.  Having joined only last week, I'm not clear on what is most immediately relevant.  Do you recommend importing all of them, as we're nearing the end of the year?

**Comment by aeiras** [comment]
Correct! 

It is the job of the monthly stewards 💛 to ensure that all git tickets are in the agenda. The creators could do that but based on actions, none does 💝
It is also the task to ensure that the close tickets get moved to complete section.

also at least 1 of the stewards needs to submit to the community call agenda under marketing section 2 parts: all tickets completed ( as shown the day before during the calls) & choose 1 or 2 items to share the work being that, answering its value etc. 

The marketing call is strategically 1 day before the community call. 

That means that when a steward cannot provide that update usually she/he gets someone else to do it. 

In the Mktg calls 5 mins are dedicated at the start of the call for this general task to “when needed” help the stewards focus on those 2 tasks amidst all the tickets. 

This December there is no community call💓 simpler-

**Comment by caitmm43** [comment]
@aeiras Okay, thank you!  And double-checking: we only import tickets from the marketing repo, not the WG repo-right?

**Comment by aeiras** [comment]
Yes. 
rarely a ticket from MPWG repo is imported to the agenda. That goes under the WG category. 

I am so happy to have your support while we close the year 🤗🥰🦄💪🏼

**Comment by caitmm43** [comment]
@aeiras  Got it.  Thank you!!  

**Confirming Some Action Items:** 
- All current open tickets are now imported to the agenda.  
- All tickets closed since the last meeting are now listed on the agenda. 

**Questions:**
- For individual tickets that are now consolidated into others, I included them only if they contained a recent update that was not posted to the consolidated ticket.  Is the correct way?  
- Are the agenda categories defined anywhere?  Similarly, what about the bracketed subjects used in ticket titles?  Some matched up, others weren't as clear to new eyes.  If this doesn't exist, can I/we add it to the onboarding wiki?  
- Does the steward need to track & import updates from either the marketing or WG google groups, or, is it the responsibility of those mentioned in each message to create tickets as needed?
- Is it better for originators to close tickets, or is it okay for anyone to do it if it's clearly resolved?  [edit: just realized this is where triage access comes in!]

**Suggestions:**
- In the case of longer threads, it took some time to figure which info was current.  I summarized this in the agenda.  Would it be helpful for the marketing steward to post this info in the ticket, clearly outlining and assigning outstanding tasks that are higher up in the thread?  
- In the comments column of each agenda row, I inserted the date created & by who.  I'm hoping this makes it easy for ticket originators to track any follow up needed.  Could this be helpful as a standard process?

**Comment by caitmm43** [comment]
**@aeiras Responding to your message _(italicized)_ about Triage GH access to all MP Repos:**  

**Done:** __"See yourself listed under the MP Infra webpage under Overview tab and check out your access . https://projects.eclipse.org/projects/technology.microprofile
https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-“Triage”-access_

**Done:** _"MPWG Repo Write GH access https://github.com/microprofile/microprofile-wg/settings/access?guidance_task="_

**Comment by aeiras** [comment]
> @aeiras Got it. Thank you!!

You are AMAZING, thank YOU! :) 
> 
> **Confirming Some Action Items:**
> 
> * All current open tickets are now imported to the agenda.
wow, i just checked, it looks wonderful. 
> * All tickets closed since the last meeting are now listed on the agenda.
you are incredible!
> 
> **Questions:**
> 
> * For individual tickets that are now consolidated into others, I included them only if they contained a recent update that was not posted to the consolidated ticket.  Is the correct way?
There is no correct way. We do our best to iterate and adjust stuff. Whatever is less work to maintain & healthy usually gets chosen. 
You can try anything you think is most efficient while you are leading the way. 
I really think what you did is helpful.  :) 

> * Are the agenda categories defined anywhere?  Similarly, what about the bracketed subjects used in ticket titles?  Some matched up, others weren't as clear to new eyes.  If this doesn't exist, can I/we add it to the onboarding wiki?

**Under agenda please check:** Agenda Template:  please use to create the minutes here or in the table format here
the links are there and maybe it is not updated with latest changes. Each Steward tends to adjust stuff a bit with the support of the entire group as necessary. 

> * Does the steward need to track & import updates from either the marketing or WG google groups, or, is it the responsibility of those mentioned in each message to create tickets as needed?

Tickets  tracking is the responsibility of everyone. Yet the ticket usually have ownership to make sure that there is someone that is keeping track of the task. Usually that person gets asked by the Steward about updates in the ticket & most often in the calls. 

> * Is it better for originators to close tickets, or is it okay for anyone to do it if it's clearly resolved?  [edit: just realized this is where triage access comes in!]

Stewards can close tickets and ought to. 
Again, the creator of the ticket could close it but that follow up usually is delayed without need. 
If we can help, we do that. When we do it, we can track it directly in the agenda so that closing the ticket is not lost on Completed tasks. 
When an owner of a ticket close it, it 99% forgets to add it to the agenda so Stewards police the up keep. 
> 
> **Suggestions:**
> 
> * In the case of longer threads, it took some time to figure which info was current.  I summarized this in the agenda.  Would it be helpful for the marketing steward to post this info in the ticket, clearly outlining and assigning outstanding tasks that are higher up in the thread?

Yes, keeping all of the data in the ticket is preferred. The ticket is the source of truth. We want it to be yet it takes discipline to protect such thing.  We are aware of it and improving. A few Contributors do not use git issues in their work so new tool onboarding takes patience and understanding. :) 

> * In the comments column of each agenda row, I inserted the date created & by who.  I'm hoping this makes it easy for ticket originators to track any follow up needed.  Could this be helpful as a standard process?

I thought that was amazing, Caitlin. 

--- 
Thank YOU so much for caring so much to enable this follow up!

**Comment by aeiras** [comment]
> **@aeiras Responding to your message _(italicized)_ about Triage GH access to all MP Repos:**
> 
> **Done:** __"See yourself listed under the MP Infra webpage under Overview tab and check out your access . https://projects.eclipse.org/projects/technology.microprofile [https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-“Triage”-access](https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-%E2%80%9CTriage%E2%80%9D-access)_
> 
> **Done:** _"MPWG Repo Write GH access https://github.com/microprofile/microprofile-wg/settings/access?guidance_task="_

Thank you for acknowledging the access. 
Today, 

1. I will send you via private the Zoom code access to become the host, help with recording to the cloud etc. Please keep the code under private key. 
2. You will also gain Admin access to MP wordpress. With it, you can choose to help with:


- adding a User as a Contributor to post content under Blog tab
- publish content on behalf of that Contributor User or MP marketing
- Add SEOs, etc
**- Please**  do not use the Admin access to adjust the Website without team acknowledgment. The site has a few sections that require human handling. Currently, only Ryan and Tetiana are in charge of any changes as seen on the tickets. :)

**Comment by caitmm43** [comment]
@aeiras I recorded today's meeting to the cloud, however I am not seeing it under cloud recordings from my account.  

I assumed I would need to manually upload it to the [Video Recordings Folder](https://drive.google.com/drive/folders/1e4Tm-zrmmc9b-8H8BW7DfXRlG6uzNqmy?usp=sharing) within the folder for Meeting Minutes.  Is that right? 

Since I used the MP admin access, does that send the recording somewhere else?  

https://github.com/eclipse/microprofile-marketing/issues/628 #628

**Comment by aeiras** [comment]
Hey Caitlin, 

Only 4 MicroProfilers (John, Kevin & Emily) have access to Zoom cloud recordings. 

Kevin is retiring so that leaves only J&E. 
Your ticket request to J&E is great. 

You don't have to do anything else with Zoom recording.  
 Youtube admins are listed under the INFRA Access under Trusted Stewards. When unsure, you can find MicroProfilers there https://drive.google.com/drive/u/0/folders/18YNojWQHb9bQoJv7PkeLnFLqSPakFhex
.

**Comment by aeiras** [comment]
@caitmm43, 

I felt inspired by your care on inventory end of the year close up. Thank you so much for the push. 
I have tackled many tickets that needed attention, closing them. They are not in the Agenda minutes under completed items yet.

**Comment by caitmm43** [comment]
@aeiras You are so welcome! They are now in the agenda under completed items (done!) :)

**Comment by aeiras** [comment]
Hey @caitmm43, 

I have completed MP publication corrections many times before with diverse media partners. 
I would love for you to have the opportunity to do it this December. Can you contact Pavel at the JRebel team and request that the article be corrected to drop the Eclipse from the MicroProfile name?

Background for you:

- MP was launched in June 2016 with its name, MicroProfile. 
When the community decided to move to the foundation, MP had to add the Eclipse to the project name. 
-- in 2020, MP was forced to become a working group to deal with its IP gaps. By doing so, it got to drop the Eclipse from its name. The Charter and the project trademarks are MicroProfile. https://www.eclipse.org/org/workinggroups/microprofile-charter.php

The current article violates the project's registered marks, and as such, it must be corrected ASAP. 
 https://www.jrebel.com/blog/eclipse-microprofile?

Questions shoot and thank you for considering this task. If you own it, it needs to have its own git issue. While your communications with Pavel will be private, the ticket stands as public tracing for that work educating a media valuable partner. :)

**Comment by aeiras** [comment]
good morning @@nsardana-bny,

While onboarding Caitlin, I noticed that you are not an WordPress Admin? Is that your choice?  
If so, totally cool and perfect to pick and choose.
If that access was overlooked, we ought to fix it.  

Caitlin has access to admin WP and could onboard you. 
Questions, shoot! :)

**Comment by caitmm43** [comment]
@aeiras 
> Hey @caitmm43,
> 
> I have completed MP publication corrections many times before with diverse media partners. I would love for you to have the opportunity to do it this December. Can you contact Pavel at the JRebel team and request that the article be corrected to drop the Eclipse from the MicroProfile name?

Sure thing!  Could you share his contact info via private?  Thanks for the background info, super helpful.

**Comment by caitmm43** [comment]
@aeiras I received a new wordpress setup link a few minutes ago.  I'm guessing that was you--thanks!  Unfortunately, the new link redirects to an [error page](https://microprofile.io/wp-login.php?action=lostpassword&error=invalidkey) that shows the same message I got last night (screenshot below).

It shouldn't have expired that quickly.  Could you assist, or should I pull in someone else? 
 
![Screen Shot 2021-12-16 at 2 39 52 PM](https://user-images.githubusercontent.com/25733252/146438251-152d1b70-9563-4c57-a28d-12c258f59570.png)

**Comment by aeiras** [comment]
> @aeiras I received a new wordpress setup link a few minutes ago. I'm guessing that was you--thanks! Unfortunately, the new link redirects to an [error page](https://microprofile.io/wp-login.php?action=lostpassword&error=invalidkey) that shows the same message I got last night (screenshot below).
> 
> It shouldn't have expired that quickly. Could you assist, or should I pull in someone else?
> 
> ![Screen Shot 2021-12-16 at 2 39 52 PM](https://user-images.githubusercontent.com/25733252/146438251-152d1b70-9563-4c57-a28d-12c258f59570.png)

Hola Caitlin, 
Many systems went down this week with the security thread. So maybe the access got re-set. All good. 
I have re-sent you new access and sent you a msg via private about it as well with pic on access. 

![image](https://user-images.githubusercontent.com/10731224/146441064-f7c4ec49-77f7-4b85-99ae-7a781859b5f0.png)

**Comment by caitmm43** [comment]
@aeiras Logged in successfully 👍

**Comment by aeiras** [comment]
> @aeiras
> 
> > Hey @caitmm43,
> > I have completed MP publication corrections many times before with diverse media partners. I would love for you to have the opportunity to do it this December. Can you contact Pavel at the JRebel team and request that the article be corrected to drop the Eclipse from the MicroProfile name?
> 
> Sure thing! Could you share his contact info via private? Thanks for the background info, super helpful.

I cannot as I don't know Pavel, who is a consultant for Jrebel. 

The first thing is that our community is so thankful that Jrebel invested time writing about MP. Thanking them is first :) 

About the how to reach out not limited to but enough for you to start your onboarding on content fixing:

1. How often the articles get fixed is by public message via twitter. 

- The dec 7th MP article didn't get pushed via the Jrebel twitter account so that cannot be done. 

2.  private email if we know the contact email 

- We don't know Pavel's email

3.  Comments in the blog to the author

- Not possible under Jrebel blogs

4. **use the publication or company contact form -**   POSSIBLE

- https://www.jrebel.com/contact-us
- write a clear git issue where all the information lives about why we request the article to be adjusted
e.g: Ticket title:  [Content] Trademark Name Fix requested on Jrebel 12/7 What is MicroProfile article
- within the git issue further suggestions for the Author:
1) Extra steps:
Once the article is fixed, if the author wishes its import to the MP blog, it can follow the https://github.com/microprofile/wpsite
the author can submit a git ticket & ask for the article to be pushed via MP social media as well. Guidelines on how: https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support

Read the article and find other things that might need fixing, as an example. Factual data is also incorrect on the section:


![image](https://user-images.githubusercontent.com/10731224/146447522-d13c80e3-a8e1-413c-928f-68bdcd9dbc92.png)

Correction: the entire article requires naming correction. 

https://docs.google.com/spreadsheets/d/1M0d7U3Yk-Vu3-TdC7zKnQ4qRVODSpD1ih2E4jvNbjoc/edit#gid=0  (MP quick facts- this will go to Q&A under the Website)

The date of Initially announced on June 27th, 2017, outside  any foundations. Its name was MicroProfile and under the MPWG continues to be formally MicroProfile. Trademarked as MicroProfile, etc. 
 
Questions, always happy to clarify!

**Comment by caitmm43** [comment]
@aeiras Sounds good.  I'm maxed out through tomorrow, so I will block time on Monday to act on this.

**Comment by nehasardana09** [comment]
Apologies for late reply. Yes I would love to get access to Wordpress. I can work with @caitmm43 on getting onboarded there.

**Comment by caitmm43** [comment]
@nsardana-bny No worries, thanks for accepting this admin access!  You will receive an email from wordpress@microprofile.io to accept and set your password.  When you are successfully registered, please confirm. 

![Screen Shot 2021-12-20 at 10 49 49 PM](https://user-images.githubusercontent.com/25733252/146867941-9bcc799a-87c0-4b47-ac10-fe2cd1d51c78.png)

**Comment by caitmm43** [comment]
I am closing this ticket with a retrospective on the experience.

For context, my comments are rooted in not only being a new steward, but also new to the MP project and new to open source.  

**Pros & Gratitude:** 
This community is awesome.  My number one observation is that critical feedback is given consistently and without judgement.  The stewards and community members made it easy to try my best, ask questions, and learn as I went.  

Special thanks to @nsardana-bny for inviting me to participate and to @aeiras for your support and guidance through onboarding.  You two made all the difference!

**Recommendations / Suggestions:** 
1. There is so much information available through github (which is great)!  The struggle is that some of it is difficult to find and could be consolidated.  I am helping @nsardana-bny with her efforts to thoroughly update the marketing stewards onboarding wiki.  I am also working on an updated wiki for WP.  

2.  I raised my hand for this responsibility without fully understanding the commitment involved.  It would be helpful to clearly explain the expectations and time commitment to future potential stewards so that they can plan their schedules accordingly.  That said, the pro's are absolutely worth it.  I'm glad I joined and I fully expect to stay on!  

Thank you all for welcoming me to this initiative.  I'm glad to be here and to be working with each of you. 

- Caitlin
