### ISSUE TITLE
[MP YouTube] Create Playlists in YouTube Channel and Add External Video

### ISSUE THREAD

**Issue by TetianaFTV** [microprofile/microprofile-marketing#613]
Hi,
As discussed on the marketing call (Nov 22), we need to create playlists on MicroProfile YouTube and add external video to be shown within the channel.

For that we need:
- gather a list of video that should be added
- decide with what playlist names these video will be grouped (language-based, topics-based, source-based)
- create these playlists, attach video, make them public

**Comment by aeiras** [comment]
@nsardana-bny, 

You mentioned your interest on helping with Youtube. Does that mean that you are ok to gain access to the MP Youtube account and help on this effort?

**Comment by nehasardana09** [comment]
Sure @aeiras. I would love to take up that role. Let me know how can I gain access.

**Comment by aeiras** [comment]
Amazing, Neha. 
Now you are the Steward on this project! :) 
Neha please create a document under Community where you can educate us on Youtube capabilities, etc so that we can help you execute stuff and do so with prompt feedback to you? 

@jclingan can you please give Neha Admin access to the MP Youtube Channel so that she can start helping with mpYoutube ? Thank you, John! 

Neha and John, https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=1113152235 is updated to include you as an Admin.

**Comment by jclingan** [comment]
@nsardana-bny, which gmail account should I invite?

**Comment by nehasardana09** [comment]
you can use neha.sardana97@gmail.com as the email address. Thanks John!

**Comment by jclingan** [comment]
Sent.

**Comment by nehasardana09** [comment]
Thanks! I will confirm soon. I got the email.

**Comment by caitmm43** [comment]
@TetianaFTV @nsardana-bny 

Hey Tetiana, Neha, 

Is this ticket still in progress, or can it be closed?  Please add your comments here and update the minutes accordingly.  Thank you!  :)

**Comment by aeiras** [comment]
Latest issues with Youtube make this project unlikely.
