### ISSUE TITLE
[Ops]  Informing the EF team about the MicroProfile 5.0 Release Date for 7th Dec and Requesting the Announcement Draft

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#619]
CC: Clark Roundy - @croundy

**The purposes of this  issue are:**

1.  Requesting to EF the Announcement draft to be provided for MicroProfilers' review, please provide it  in Word version with Suggestive Mode access at least 3 days (avoid a Friday delivery) before Dec. 6th. 
1.  Stating that we will insert our Technical blog to that paid release
1.  Following all EF updates related to the process

Notice that EF can use the https://groups.google.com/g/microprofile-marketing repository to submit the release for review.

**Tasks:**

- [ ] EF MP 5 release announcement using the EF channels.

**Comment by croundy** [comment]
EF does have a MicroProfile 5.0 press release on the docket, but has not yet assigned a date. Per the plan recently discussed, a white paper will also be created and promoted at the time of the press release. As this process has only recently started and the white paper will not be completed until after the first of the year, we would suggest a more coordinated effort with a promotional date targeting a mid to late January announcement and promo.  There is mention of a blog as well. If there is a draft blog available, we can use that to get started in drafting the announcement.

**Comment by aeiras** [comment]
Good morning, Clark. 

The MP community has chosen the release date to be on Dec 7th, That date is set and won't be changed. 

The White paper is expected in 2022. 
The announcement should come the week of the release. Is that possible? 
Otherwise, can we allocate that money to swag?

Thank you,

**Comment by croundy** [comment]
Sorry Amelia. Today is not an appropriate time to be asking for a press release to be written and properly promoted for the 7th of December. It's not going to happen and no the money can't be reallocated for swag. As has previously been communicated, the programs outlined and presented have been committed to and are in process. This last minute timeline that has been suggested does not flow with normal marketing processes and such an expectation to plan, promote and have a good outcome is completely unrealistic.

Let's reset expectations and do this right. 

Thanks,

Clark

**Comment by croundy** [comment]
A good starting point will be to send us key messages and the draft blog post referenced by Emerson

**Comment by dblevins** [comment]
@emecas can you provide that to Clark?

@croundy thanks for the understanding.  Again, apologies if things are looking last minute.  The community has been aiming since late summer to get the 5.0 release out before the Dec 7th JakartaOne Livestream event so it can be announced/promoted at that event.   Emily is doing a MicroProfile 5 talk at that event, IBM has an OpenLiberty release planned and should be cut in the next week, and the working group has already finished two-week voting periods and released the majority of the component specs that make up MP 5.0.  It's just the last MP 5.0 umbrella spec that's remaining and that vote is planned to start next week.  Hope that provides good context.  I'm not sure anyone can stop the release train at this point, so we're likely in a do the best we can scenario with any paid announcements and the community is likely going to have to live with whatever we get in that regard.

**Comment by croundy** [comment]
@dblevins Thanks for the additional color on this topic. Personally I see no issue with talking about MicroProfile 5.0 at JakartaOne and making it an important part of your messaging there. At the same time, from a macro perspective, the WG will get a lot more mileage out of this announcement if there is a more coordinated effort and other assets to help tell the story as to why 5.0 matters......thus the white paper. Might I suggest a 2 phase approach:

1. Soft launch for December 7th. Preferably more of a tease than a full on release...a sneak preview of what 5.0 is all about, with the promise of more details to be announced at a later time. The blog post could mirror this strategy. If this group can help with messaging, we can perhaps put a release out on the wire that teases 5.0 and mentions the presentations and discussions at JakartaOne.

2. Do a more formal launch in January/February that includes the white paper, perhaps another more detailed blog post and a press release with more details, use case info, etc. around the 5.0 release. This also gives our PR organization time to talk to media, get interviews lined up, etc.  

WDYT about this kind of approach to try to maximize coverage and benefit from MicroProfile 5.0?

**Comment by emecas** [comment]
> @emecas can you provide that to Clark?
> 

Sure!!!

@dblevins  @croundy  here you have a couple of related issues with comparable content:

- https://github.com/eclipse/microprofile-marketing/issues/548
- https://github.com/eclipse/microprofile-marketing/issues/546

and here is the link to the template used for MP 4.0/4.1 release:

- https://docs.google.com/document/d/1cWZASF0krdnuuOdwFJoFR69w6NurPqbsafwsvqie0DE/edit#

**Comment by croundy** [comment]
@emecas thanks for the links though it's not clear the expectation here. All links seem to be focused around 4.0/4.1. If there is a 5.0 release document and announcement blog, please share that with me so we can work with our team on a press release.  Thanks

**Comment by aeiras** [comment]
@croundy, 

Do you have the wiki on how WG can collaborate with you and the team on Project releases?  Sharing it will set us for a successful outcome as that document will inform us of deadline request (minimum) + more stuff that is required from the community side.  As soon as you send it our way, we will add it to the wiki I shared with you yesterday on https://github.com/eclipse/microprofile-marketing/wiki/Eclipse-Foundation-Team-GitHub-IDs

MP 5.  is an infra release catching up to Jakarta 9.1. It has no new features. 
The technical paper ideally is not on 5 but actually in a future MP release that contains valuable technical content. 

In 2022 MPWG will go back to 3 yearly releases focusing on features and not infra. 
Feb, June and Oct. 

Can the Release annoucement budget be transferred to 1 MP of the 3 releases (preferable chosen by the MPWG) in 2022 instead? 

We cannot stop the 5.0 release.  We have plans to include the support of the infoQ team, who is already  working on the write up for the  5.0 release via the GSJUG member's contribution. 

Thanks for the follow up. 

Emerson, great job on providing the documentation.

**Comment by aeiras** [comment]
Clark for reference, this wiki guideline is our preferred process for Releases. https://github.com/eclipse/microprofile-marketing/wiki/Marketing-Release-Process
When in collaboration with the EF, we will want the EF formal Release announcement Services -  wiki document, in within the document to establish a clear road. I hope this helps.

**Comment by dblevins** [comment]
@croundy I don't think there is any way for us to get a consensus on a new plan for the Dec 7th Livestream as our next Tuesday call is dedicated to finalizing the 2022 program plan and 5.0 was wrapped up to ensure we had time to dedicate to finalizing the 2022 plan.  We certainly could do additional things to promote the release in January / February as long as they used the 2021 budget.  Best way to do that would be to join the next Marketing meeting and throw out some ideas.  I'm not 100% sure when that is as I know there was discussion of cancelling some December meetings.

**Comment by dblevins** [comment]
> @emecas thanks for the links though it's not clear the expectation here. All links seem to be focused around 4.0/4.1. If there is a 5.0 release document and announcement blog, please share that with me so we can work with our team on a press release. Thanks

Right.  @emecas as I understood, you, @ederks85 and @Emily-Jiang volunteered to write the blog post for microprofile.io for 5.0.  The foundation would likely need that before they could be of much use.  Do you think you could have that drafted by say Monday or Tuesday next week?  Certainly for purposes of microprofile.io it could be done as late as early Dec, just that doesn't allow Clark to help -- press releases are paid and need to be scheduled usually one or two weeks in advance, so we're already in the "danger zone" if we want that option.

**Comment by croundy** [comment]
There seems to be some confusion around this issue. To be clear, EF will not be creating release documentation for MP 5.0. This content needs to come from the experts within the MP organization and according to your established protocols and processes. It is those documents, along with additional input from experts/members of the community that will help the EF team create the assets outlined in the plan. As a reminder, our commitment is to do the following:

1. Help craft and promote a press release around MP 5.0 based on the messaging and documentation you provide; 
2. Create a white paper based on interviews (to be scheduled) with MicroProflie SMEs; and
3. Edit and/or otherwise assist with 1 or more blog posts supporting MP 5.0, and help promote those assets. 

All of the above items will require WG participation in the form of key messages and MP 5.0 release information.  What I'm hearing from this conversation is that as of right now there is no release document or draft blog available that describes or messages MicroProfile 5.0. In terms of EF processes, those are the starting points, so please make this a priority. 

It pains me that we are just now beginning this process and that we are now in this uncomfortable position. Unless an immediate effort is made by this group to help drive the messaging around a press release in support of MicroProfile 5.0 release, there is really no action to be taken by EF at this time.  Rather, our focus will continue to be on the items laid out in the plan and described above with deliverables flowing into the next year. As previously confirmed, the 2021 budget will be fully allocated and will not carry over into the new year.

**Comment by dblevins** [comment]
@croundy Thanks, Clark.  What you say makes sense and is how I've understood how the foundation likes to engage with projects; support the experts, not be the experts.   On the "uncomfortable" position, I know the community was planning to do the 5.0 release announcement on its own as it's done for previous releases.  I think this ticket was filed due to recent communication that there was some 2021 budget allocated to an announcement; I'm not 100% confident I understand how things were allocated.  Either way, it's understood your hands are tied.  If there was budget allocated to a 5.0 press release, hopefully those who've volunteered to write the blog post can get something in your hands early next week.

**Comment by Emily-Jiang** [comment]
Thank you @dblevins @aeiras for kicking off this activities! I understand that we will write the blog to announce MicroProfile 5.0 same as previous releases. I plan to get it done early next week, hopefully by Monday. Then EF can take that as input to do further promotion and press release. I will announce MP 5.0 release at JakartaOne Live during my session. InfoQ can write a blog as well. EF can do the press release based on the blog I am going to write or other available materials around MP 5.0. Your press release might happen in Jan and it is under your control. Is my understanding correct @croundy?

**Comment by croundy** [comment]
@dblevins yes you've got it right. The announcement is in the form of a press release. As mentioned, I would prefer that we do this right and make some noise around MP 5.0, which does require a bit more runway as we would like our PR folks to reach out to members of the media in advance and potentially line up additional opportunities for members to speak with editors. Depending on how things come together with the blog and messaging, we may be able to at least augment the announcement at JakartaOne with a press release, but please understand that the foundation already has other press releases going out that day/week, so no promises. Will make a best effort. If not, we can still do a press release at a later date with a slightly different spin....something that complements and introduces the white paper perhaps. @Emily-Jiang does this answer your question?

**Comment by Emily-Jiang** [comment]
@croundy sounds good. We will do our own release and make the blog available to you asap. If you could at least put up a poster on the JakartaOne Live, it will be a good start and then more detailed PR can happen at a later date such as Jan (prior to the first release in 2022).

**Comment by croundy** [comment]
@Emily-Jiang sounds like a good plan. Let me speak with the folks planning JakartaOne Live. Is there a poster/image design or concept you have in mind?

**Comment by aeiras** [comment]
> @croundy sounds good. We will do our own release and make the blog available to you asap. If you could at least put up a poster on the JakartaOne Live, it will be a good start and then more detailed PR can happen at a later date such as Jan (prior to the first release in 2022).

@Emily-Jiang @emecas & @ederks85 Ideally, the technical blog has you 3 as the authors. I will volunteer to be the Editor of the blog. Tetiana will help with publishing + more. 
Please pull me in via that new ticket as soon as the draft is ready for review. :) 

I am so very excited release 5 will be done as planned Dec 7th. Let's do this!

**Comment by Emily-Jiang** [comment]
@croundy https://drive.google.com/drive/folders/1XqoNB9kEL9dpKxjHq71a4CfmBx1vjt3Z has all of the materials for MicroProfile 5.0 release. Please take any info as you see fit for a quick announcement.

**Comment by caitmm43** [comment]
@emecas @Emily-Jiang @croundy @dblevins @aeiras 

Hello all, is this ticket complete?  If so, please close and update the minutes accordingly.  Thank you!  :)

**Comment by Emily-Jiang** [comment]
Since we discussed this ticket at yesterday's call, I thought it might be a good idea to briefly mention where we are on this based on my knowledgment. The press release is being draft after a few techinical interviews with a few MP individuals. The article is at the reviewing stage. @croundy please add anything I missed.

**Comment by emecas** [comment]
Closing this issue based on the:
[MicroProfile Whitepaper Project](https://docs.google.com/document/d/14j3Ac1Se1hBONDhhGlDIyR05CjDwpHIn/edit) : **MicroProfile Is the Right Choice for Enterprise Java Microservices**

Additional details available in this [thread](https://groups.google.com/g/microprofile-marketing/c/Ote3EBaBoR4/m/A2o9aBOOCQAJ?utm_medium=email&utm_source=footer)


Special thanks to @jclingan for enabling community and working group to complete the review process as well as all reviewers:
@Emily-Jiang , @aeiras , @dblevins , Michael Redlich , Cesar Hernandez, Kathy Pendergast, Majid Mostafavi
