### ISSUE TITLE
[Social Media]2022 - Prospectus 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#664]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**

Organizations join the MicroProfile Working Group, MPWG, because Enterprise @java Microservices is essential to their communities. The #MicroProfile Prospectus answers why you should consider joining the open and vendor-neutral #MicroProfileCommunity.

http://bit.ly/mp-prospectus

**Schedule**
Twice per month

**Design Card**

use elements from the document

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> Organizations join the MicroProfile Working Group, MPWG, because Enterprise @java Microservices is essential to their communities. The #MicroProfile Prospectus answers why you should consider joining the open and vendor-neutral #MicroProfileCommunity.
> 
> http://bit.ly/mp-prospectus

**How about:**
Why should you join the #MicroProfileCommunity, MPWG? Short version: Because Enterprise @java Microservices are essential to our communities. For the long version, check out the #MicroProfile Prospectus to learn how the open and vendor-neutral #MicroProfileCommunity benefits you. 

http://bit.ly/mp-prospectus

**Comment by rstjames** [comment]
![MicroProfile-Prospectus-2022](https://user-images.githubusercontent.com/12132146/154092806-067e220f-7152-4d9d-bef5-3dcdb3131eb4.png)

**Comment by rstjames** [comment]
all set for the year
