### ISSUE TITLE
[Documentation] Create MP Committer Representative Role Description

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#676]
From minutes hangout 02/01/2022:

Edwin will start writing a Committer Representative role description + Amelia will provide draft/edit support to the document before it becomes a Wiki.

**Comment by aeiras** [comment]
I am right beside you, Edwin. Thank you for choosing to document stuff relevant to the responsibilities of the Rep. Your actions are truly a wonder! :) 

Pull me in as you see fits.  No deadlines, your project, your time! 👍

**Comment by ederks85** [comment]
Document that will contain the role description: https://docs.google.com/document/d/1X5kILS_hnHfQgxG1nphV9_vosWCIDaDnDeEIq_pmKv4/edit?usp=sharing

**Comment by ederks85** [comment]
@aeiras I have an initial draft of the document ready. Could you please take a look and let me know what you think?

**Comment by aeiras** [comment]
Hola @[ederks85](https://github.com/ederks85)

I will get to the document by Friday. Thank you for your patience and awesome you got it the draft ready. Let's do this! :)

**Comment by aeiras** [comment]
hola @ederks85, 

I enjoyed reviewing the MPCR document. It shows your care in each section. 
Feedback is sent. Looking forward to making it stronger with you!

**Comment by ederks85** [comment]
@aeiras I have made a significant update to the document based on your input. Can you please have another look?

**Comment by aeiras** [comment]
Edwin, 

Fantastic improvements, I only had a few notes. It reads wonderfully. 

Please feel free to convert it into a wiki after you have seen what is left from today's review: https://github.com/microprofile/microprofile-wg/wiki. I believe you have to Write access to the MPWG repo :) 

I had fun contributing to such an important piece for MP. You rock! 

PS: it is your responsibility to communicate the wiki to the Community via its forum. Own it nicely and keep being awesome. 

I will move the word document under the Committer Rep folder and adjust its edit to "public view" instead of edit for all. 
Happy wknd,

**Comment by ederks85** [comment]
All input has been processd 👍

**Comment by ederks85** [comment]
All input has been processed, I will transfer it to the Wiki if you have no further remarks

**Comment by aeiras** [comment]
transfer it away. The document will live and accept PRs or edits :) it is a great start. Hugs, Edwin!

**Comment by ederks85** [comment]
Document transferred to Wiki: https://github.com/microprofile/microprofile-wg/wiki/Committer-Representative-Role-Description

Also distributed on community mailing list

**Comment by aeiras** [comment]
Happy Friday, @ederks85 

Offboarding yourself from being 2021 MPCR with the wiki is pretty fantastic. Kudos to you for choosing to share and enable others to step into the spot light and own that much responsability for the project. :) 

It is vauable you sent the wiki to the Dec 1st MPCR, fantastic follow up to that conversation. 
I recommend you consider starting a new thread so that the wiki is not hidden on a "related" topic as well.

**Comment by aeiras** [comment]
Edwin, 

I have updated the Members Onboarding Wiki with the MPCR :) https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Working-Group:--Members-Onboarding
