### ISSUE TITLE
Update spreasheet "MicroProfile Steering Committee Representatives" and website link to 2022 tab

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#701]
Issue:

1. Go To https://microprofile.io/workinggroup/ 
2. Click on "Members" (attached screenshot) ![image](https://user-images.githubusercontent.com/1454523/179823463-33fe08c3-01a0-4c73-a748-e706b79fb4ee.png)
3. The spreadsheet opens in the Year 2021, and the format for font size and Strikethrough text for tab 2022 differs from the other tabs.

Proposal for fixes:

1. Microprofile contributors with Write access to the [MicroProfile Steering Committee Representatives](https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit#gid=1486862268)
the spreadsheet can fix the format, and remove the rows that contain Strikethrough text.

2. Microprofile with WP engine access can update the link for "Members" to point at the 2022 spreadsheet tab.

Nice have (feel free to open a new GitHub issue if agreed):
- Replace the spreadsheet with a wp engine page dedicated to Members.

**Comment by aeiras** [comment]
@cesarhernandezgt, 

We cannot adjust the write access to the this MPWG drive as it is managed by the EF. 

@rstjames, 

Can you manually adjust to current tab? 

Thank you,

**Comment by cesarhernandezgt** [comment]
Proposal for an incremental approach. 
As presented over the Aug 29th Mkt call.

The spreadsheet logos will go in this new tab.
![image](https://user-images.githubusercontent.com/1454523/187266930-09011c81-1cf2-4e1d-9c8e-b03f33500232.png)

**Comment by rstjames** [comment]
@cesarhernandezgt sorry little confused what should be done in this ticket. 
- new members tab
- what goes under that tab?  Logos? spread sheet link?

**Comment by cesarhernandezgt** [comment]
@rstjames 
Under the members tab, the information I recall we discussed for each Organization was:

- Organization	Name
- Organization Logo
- Representative
- Alternate

**Comment by rstjames** [comment]
@cesarhernandezgt here is the latest update. I did not add the company logo because of the amount of width we have with this layout. Thoughts? (this screenshot is zoomed out a bit)

<img width="1205" alt="Screenshot 2022-10-06 at 13 05 56" src="https://user-images.githubusercontent.com/12132146/194297725-71d804be-1a78-420e-b377-fc09b904b37b.png">

**Comment by aeiras** [comment]
The new section looks good, @cesarhernandezgt and @rstjames. 

Thank you, Ryan, for cleaning this section, you rock! 

**Feedback**

1.  Standarization of corporate names  
- Atlanta Java User Group (AJUG)
- Garden State Java User Group (AJUG)
- Association of the German Java User Groups (iJUG)
- Tomitribe 
- Fujitsu Global

**2.  Add Missing Member**

- Committer Representative   (N/A) 

**3.   Nice to see in the page (can it be done since changes are not every week? )**

- add the corporate website links to the members
- add the Twitter link to the people 

4. **Related to the Knowledge section, adjustments required** 

- First sentence re-write:         the MPWG [Charter ](https://www.eclipse.org/org/workinggroups/microprofile-charter.php)7 pillars: Limited processes, Experiment and innovate, No backward compatibility guarantee, Implementation first, Encourage brand adoption, Openness, & Low barrier to entry are protected.

- Insert Steering Minutes to new section, Members:    The Steering Committee Discussion [Minutes](https://drive.google.com/drive/folders/1FKOKGwHnS-eHujVKs5BL6U3xCqyoS7P8) provides the history of all the committee discussions that have happened, since October 1st, 2020, that is approved by the members.

- Delete the Minute's sentence from the Knowledge area. 

Happy to clarify if anything is unclear.

**Comment by rstjames** [comment]
@aeiras 
3. Nice to see in the page (can it be done since changes are not every week? )

add the corporate website links to the members 
add the Twitter link to the people

 _**I can not do this, this element has some limitations in WP but can talk to Andrii about it**_

**Comment by rstjames** [comment]
the other adjustments are made

**Comment by aeiras** [comment]
> @aeiras 3. Nice to see in the page (can it be done since changes are not every week? )
> 
> add the corporate website links to the members add the Twitter link to the people
> 
> _**I can not do this, this element has some limitations in WP but can talk to Andrii about it**_

it is totally OK to pull Andrii to this task, Ryan.  Before he starts, we need to know what will it take.  Do keep us post it on the nice-to-have feature. :)

**Comment by rstjames** [comment]
Atlanta Java User Group (AJUG) - https://ajug.org/
Garden State Java User Group (AJUG) - https://gsjug.org/
Association of the German Java User Groups (iJUG) https://www.ijug.eu/de/home/
Tomitribe- https://www.tomitribe.com/
Fujitsu Global - https://www.fujitsu.com/global/
IBM - https://www.ibm.com/
Oracle- https://www.oracle.com/
Redhat- https://www.redhat.com/
microsoft https://www.microsoft.com/

**Comment by Dexmaster** [comment]
Hello, I've done two subtasks:

- add the corporate website links to the members (done)
- add the Twitter link to the people (done)

![image](https://user-images.githubusercontent.com/6061000/197028116-f7fee105-6f5b-4da5-abe0-d5aadf428329.png)

Ok, so I've:

- added a `[linkify]` shortcode so as to be most futureproof
- added the above corporate website links to the members
- searched and found most of the Representatives' Twitter handles 

@aeiras / @rstjames please check: https://microprofile.io/workinggroup/
There are still 4 Twitter handles missing, I've found linked-in for one person if we want to have some alternative for people we can do that, otherwise, I'm out of options.

P.S. `[linkify]` shortcode examples:
```
[linkify link="https://www.tomitribe.com/"]Tomitribe[/linkify] 
[linkify twitter="dblevins"]David Blevins[/linkify]
```
![image](https://user-images.githubusercontent.com/6061000/197027283-a7611403-0f01-47e8-9fa8-8ae5f61779ec.png)

**Comment by aeiras** [comment]
Great job, Andrii and Ryan!!

Below are the missing tweet IDs @Dexmaster 

https://twitter.com/mpredli  for Michael 
The other two MicroProfilers likelt don't have Twitter. I will follow up with them and if they, lets add Github.  Do you think that integration is possible, Andrii?

**Comment by kazumura** [comment]
@Dexmaster 
Please remove "Global" from "Fujitsu Global".

**Comment by Dexmaster** [comment]
@aeiras Sure we can do linkedin or github icon, anything that represents them. Also there are 3 missing twitter handles at this moment Nathan Rauh (IBM), Jan Westerkamp (iJUG) and Takahiro Nagao (Fujitsu).

@kazumura Done.

**Comment by aeiras** [comment]
Good stuff, Andrii. 

Hola beautiful Kenji @kazumura, do you know what social media Takahiro prefers? The page can link to anything he prefers. Thank you for helping on this!

**Comment by kazumura** [comment]
> Hola beautiful Kenji @kazumura, do you know what social media Takahiro prefers? The page can link to anything he prefers. Thank you for helping on this!

Please use "@tnagao7".

**Comment by Dexmaster** [comment]
Ok, so for the last two Representatives used their GitHub handle.
You can review changes on: https://microprofile.io/workinggroup/

![image](https://user-images.githubusercontent.com/6061000/197070209-9104db2a-4450-4c30-933d-41a9d2fdcfd2.png)

**Comment by rstjames** [comment]
Thanks for the help @Dexmaster
