### ISSUE TITLE
Mention stand-alone specs on microprofile.io

### ISSUE THREAD

**Issue by kito99** [microprofile/microprofile-marketing#718]
When coming to the microprofile.io, it's not clear that non-core specs (ones not shown on the landing page) exist. On the [Projects](https://microprofile.io/projects/) page, some non-core specs are listed, but they're not denoted as such, and they're mixed in with projects like the master bom repo. 

From an end-user perspective, I'd like to be able to see all that MicroProfile has to offer, but it's hard to see that from the existing site. Ideally, at a minimum, the Projects page would have all non-core specs, and differentiate between core specs, non-core specs, and others (bom, examples, etc.). I also think the landing page should make it clear that some implementations offer the non-core features as well.

**Comment by kito99** [comment]
@aeiras where can I find instructions on how to contribute?

**Comment by aeiras** [comment]
Hola dear Kito, 

@cesarhernandezgt , Summers, Emily, and a few others used to meet every Friday in the AM to discuss Website improvements. Due to summer, the calls have stopped.  The Projects' page will likely require those calls to strategically return for skeleton work on "must-have."  We use all the feedback received to create the outlines for future Website work. 

You can continue to submit git issues and discuss them via microprofile-marketing@googlegroups.com. 
 If a marketing ticket doesn't get attention within seven days, such emails are expected as a "help wanted".  However, all website improvements do not fall under the 7- day- deadline due to the required collaboration and discussion during the Marketing calls that happen twice a month on Mondays 10 am-11 am PDT.  Please keep that in mind. 

Great to have you here!

**Comment by cesarhernandezgt** [comment]
Hi @kito99 ,

I agree with the description of this GitHub issue.

We still need to complete a migration the website has been receiving during this past couple of months related to migrate website backend from ec2 backend into GitHub pages(actions). This migration is been tracked in https://github.com/microprofile/microprofile-wg/issues/65. 

The actual work for the migration is happening on: https://github.com/microprofile/microprofile-site where https://github.com/microprofile/microprofile-site/issues/121 gives an overview of the missing migration.

I think this Github issue can be transferred into https://github.com/microprofile/microprofile-site; so fare we have a couple of after-migration GitHub issues tracked with the tag `nice2have`.

**Comment by kito99** [comment]
Thanks @cesarhernandezgt. Moved to https://github.com/microprofile/microprofile-site/issues/123.
