### ISSUE TITLE
[Blog Contribution] Which technical route should I choose to build cloud-native microservices?

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#750]
**[MicroProfile.io WordPress](https://github.com/microprofile/wpsite)**

 **MicroProfiler**
 To new Contributors who need to gain access to the WordPress site, please provide:
- [ ]   Name:
- [ ]   Email:

**Content copy/edit review (available & optional)
- [x]  [Draft in WP](https://microprofile.io/wp-admin/post.php?post=7092&action=edit)
 
 **Social Media Description**
 - [ ]   构建云原生微服务，我该选择哪种技术路线？By @emilyfhjiang. 翻译： 赵欣

(That text is the title plus the name of the original author (in English; Emily) and the translator (into Chinese).

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
I'm tagging in @Emily-Jiang as she should be able to help if you have any questions about content itself. Emily wrote the original article for the Eclipse Newsletter in English. It's been translated into Chinese (by someone else) and the Chinese version is now published on the Open Liberty blog (which is what this MP blog entry links to). It's a post about how to write cloud-native microservices using MP/Spring.

**Comment by aeiras** [comment]
Hola @lauracowen, 

The article is from 2019 which requires an updated version before it can be imported to MP.io content. 

Reasons for rejection of contributing blog:

- the 2019 article has good information, yet a lot has changed since then that goes beyond code and requires attention with potentially a revision of content if @Emily-Jiang chooses to own such work :)  
- MicroProfile reverted to its original name on Oct 1st, 2020. For this or any MP content contributions, the name of the Project is MicroProfile.   If 2022 and onwards we continue to accept the Eclipse MP, it will violate the project trademarks and will continue to cause issues with branding and the Mark.  

I will close this ticket for now with the hopes that the information provide is helpful and provides insight about YES. Old MP posts are welcomed with re-writes that pay close attention to the current status. :) 

Thank you, Laura!
