### ISSUE TITLE
[Social Media] Pay for Twitter Blue?

### ISSUE THREAD

**Issue by m-reza-rahman** [microprofile/microprofile-marketing#757]
I am paying for Twitter Blue personally and the Jakarta EE Ambassadors are doing the same. So far, it seems to be worth it in terms of increasing the visibility of tweets and getting more followers. I think MicroProfile should consider paying for Twitter Blue.

**Comment by aeiras** [comment]
Hey Reza, 

How many followers have Jakarta Ambassadors' Twitter gained monthly since paying for Twitter blue? 

-- **Below is a short Insight of what currently is MP Social media infra and management** --
MP gained over 59 followers (1/30 stats) on Twitter in January. 

MP social media is managed 100% by MicroProfilers. The Payment of Twitter blue seems problematic as it will require a credit card and closed-up management of social media.  There is a strong desire for the project to continue its fluidity with diverse access in all its INFRA without restrictions, as each MicroProfiler is always listed under Infra inventory MicroProfilers' access. 

All media volunteers [  Infrastructure Admins](https://microprofile.io/workinggroup/#mptab-knowledge)) are listed. Please check access to media via Hootsuite, Twitter, etc.

**Comment by m-reza-rahman** [comment]
It's still very early days, so hard to say anything deterministic. Both the Ambassadors' account and my personal account has grown by ~100 since purchasing Twitter Blue early January. That's a much faster rate than many prior months, probably by ~100% or more.

**Comment by rstjames** [comment]
This was discussed on the marketing call and we came to the decision that we don't see the value at this time. Maybe we should look back into this later on as our marketing/ SM increases,
