### ISSUE TITLE
[Blog] Review blog post 

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#98]
Hello everyone, I just wrote a blog post about managing file uploads on MicroProfile, can you review it please?

English (https://microprofile.io/wp-admin/post.php?post=6230&action=edit)
Spanish (https://microprofile.io/wp-admin/post.php?post=6227&action=edit)

thanks!

**Comment by aeiras** [comment]
@Motojo 
Hola Jorge, justo he termindo de revisar tus blogs. Both published, thank YOU for prioritizing your MP knowledge & writingTHEcode in Spanish and English, it is amazing. Fun side--  Once you tweet them, we will re-post that tweet via MP handle. 

**Note:** I made a few grammatical adjustments to the English version. Please check why I adjusted "we" to developers and a few other minor changes.

**Comment by cajasmota** [comment]
@aeiras 
Gracias Amelia! El primero de muchos post que tengo en mente :smile: 

It's the second time I write a blog post in english, so any feedback is appreciated :+1:

**Comment by aeiras** [comment]
I think you did great for being your 2nd blog, impressive. Next time, we will use MP drive folder for you to get direct help by our copy/editor Peggy. 
This time, due to 1 week submission and that you submitted both blogs at once, I wanted to be the one to review blogs to compare and understand YOU via writing. :) Super fun! 

Tweet so we can highlight how truly amazing you are and thank you LatinArmada!
